# ${CORP_SLUG}-managed: generated by ${CORP_NAME} launcher v${CORP_LAUNCHER_VERSION}
# Managed by ${CORP_NAME} — do not edit by hand
# Powered by ${CORP_POWERED_BY}
#
# This file is rewritten by the launcher installer. To change any value,
# edit the launcher templates and re-run the installer — hand-edits will
# be overwritten on the next install/update.
#
# tpl: Continue.dev reads this from ~/.continue/config.yaml by default
# tpl: (overridable via $CONTINUE_GLOBAL_DIR). Continue supports its own
# tpl: runtime substitution syntax `${env:VAR}` which is resolved when the
# tpl: IDE extension starts — we use it for the API key so the secret is
# tpl: never persisted to disk, only the placeholder is.
# tpl:
# tpl: Skill-time substitution: ${VAR}   (resolved by the launcher renderer)
# tpl: Runtime substitution:    ${env:VAR} (resolved by Continue at load)

name: ${CORP_NAME}
version: 1.0.0
schema: v1

# tpl: ---------------------------------------------------------------------
# tpl: Primary chat / edit / apply model — pointed at the corporate gateway
# tpl: (LiteLLM / Azure / Bedrock proxy, OpenAI-compatible).
# tpl: ---------------------------------------------------------------------
models:
  - name: ${CORP_NAME} Primary
    provider: ${LLM_CONTINUE_PROVIDER}
    model: ${LLM_PRIMARY_MODEL}
    apiBase: ${LLM_OPENAI_BASE_URL}
    apiKey: ${env:CORP_API_KEY}
    roles:
      - chat
      - edit
      - apply
      - summarize
    defaultCompletionOptions:
      temperature: 0.2
      maxTokens: 4096
    requestOptions:
      timeout: 60000
      verifySsl: ${LLM_VERIFY_SSL}
      caBundlePath: ${CORP_CA_BUNDLE_PATH}
      proxy: ${CORP_HTTPS_PROXY}
      noProxy: ${CORP_NO_PROXY}
      headers:
        User-Agent: ${CORP_SLUG}-launcher/${CORP_LAUNCHER_VERSION}
      clientCertificate:
        cert: ${CORP_CLIENT_CERT_PATH}
        key: ${CORP_CLIENT_KEY_PATH}
        passphrase: ${env:CORP_CLIENT_KEY_PASSPHRASE}

  # tpl: -------------------------------------------------------------------
  # tpl: Tab autocomplete — smaller, faster model. Same gateway.
  # tpl: -------------------------------------------------------------------
  - name: ${CORP_NAME} Autocomplete
    provider: ${LLM_CONTINUE_PROVIDER}
    model: ${LLM_WEAK_MODEL}
    apiBase: ${LLM_OPENAI_BASE_URL}
    apiKey: ${env:CORP_API_KEY}
    roles:
      - autocomplete
    autocompleteOptions:
      debounceDelay: 250
      maxPromptTokens: 1024
    requestOptions:
      timeout: 15000
      verifySsl: ${LLM_VERIFY_SSL}
      caBundlePath: ${CORP_CA_BUNDLE_PATH}
      proxy: ${CORP_HTTPS_PROXY}
      noProxy: ${CORP_NO_PROXY}

# tpl: ---------------------------------------------------------------------
# tpl: Embeddings — disabled for corporate by default. Local indexing only
# tpl: avoids shipping source code chunks to a third-party embeddings API.
# tpl: To enable, point at the gateway with a dedicated embed model.
# tpl: ---------------------------------------------------------------------
embeddingsProvider:
  provider: none

# tpl: ---------------------------------------------------------------------
# tpl: Context providers — what Continue can pull into the prompt window.
# tpl: Conservative set: only what is already on the developer's machine,
# tpl: nothing that hits external APIs.
# tpl: ---------------------------------------------------------------------
contextProviders:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase

# tpl: ---------------------------------------------------------------------
# tpl: Slash commands — the built-in trio. Custom flows go in customCommands.
# tpl: ---------------------------------------------------------------------
slashCommands:
  - name: review
    description: Review the current diff for issues
  - name: edit
    description: Edit the highlighted code
  - name: share
    description: Export the current chat session

# tpl: ---------------------------------------------------------------------
# tpl: Custom commands — empty by default; tenants can append their own.
# tpl: ---------------------------------------------------------------------
customCommands: []

# tpl: ---------------------------------------------------------------------
# tpl: Telemetry / experimental — both off. Non-negotiable for corp.
# tpl: ---------------------------------------------------------------------
allowAnonymousTelemetry: false

experimental:
  useAlternativePersonality: false
