#!/usr/bin/env bash
# =====================================================================
#  ${CORP_NAME} — Continue.dev launcher installer
#  Powered by ${CORP_POWERED_BY}
#
#  Idempotent. Re-runnable. Backs up files before modifying them.
#  - Detects OS + shell RC (zsh / bash / fish)
#  - Detects supported IDEs (VS Code: `code`, JetBrains: `idea`/`pycharm`/`webstorm`)
#  - Optionally installs the Continue extension for VS Code
#  - Renders a managed ~/.continue/config.yaml (handled by render.py)
#  - Backs up any pre-existing ~/.continue/config.yaml
#  - Wires an idempotent ${CORP_SLUG} function block into the shell RC
#  - Stores the API token via the shared secrets-store.sh
# =====================================================================

set -euo pipefail
umask 077

INSTALL_DIR="$(cd "$(dirname "$\{BASH_SOURCE[0]\}")" && pwd)"
LAUNCHER_VERSION="${CORP_LAUNCHER_VERSION}"

# tpl: ---------------------------------------------------------------------
# tpl: Colors — TTY only
# tpl: ---------------------------------------------------------------------
if [ -t 1 ]; then
    ORANGE="\033[38;5;${BANNER_COLOR_PRIMARY}m"
    GREEN="\033[32m"
    RED="\033[31m"
    YELLOW="\033[33m"
    BOLD="\033[1m"
    DIM="\033[2m"
    RESET="\033[0m"
else
    ORANGE=""; GREEN=""; RED=""; YELLOW=""; BOLD=""; DIM=""; RESET=""
fi

info()  { printf '  $\{GREEN\}[OK]$\{RESET\} %s\n' "$*"; }
warn()  { printf '  $\{YELLOW\}[!]$\{RESET\}  %s\n' "$*"; }
fail()  { printf '  $\{RED\}[KO]$\{RESET\} %s\n' "$*" >&2; }
step()  { printf '\n$\{BOLD\}%s$\{RESET\}\n' "$*"; }
ask()   { printf '  $\{YELLOW\}%s [y/N] $\{RESET\}' "$*"; read -r ans; case "$ans" in [yY]*) return 0 ;; *) return 1 ;; esac; }

# tpl: ---------- detection ----------
detect_os() {
    case "$(uname -s)" in
        Darwin*) OS_TYPE="macos"; OS_LABEL="macOS $(sw_vers -productVersion 2>/dev/null || echo '')" ;;
        Linux*)
            if grep -qi microsoft /proc/version 2>/dev/null; then
                OS_TYPE="wsl"; OS_LABEL="Windows (WSL)"
            else
                OS_TYPE="linux"; OS_LABEL="Linux"
            fi
            ;;
        MINGW*|MSYS*|CYGWIN*) OS_TYPE="gitbash"; OS_LABEL="Git Bash (Windows)" ;;
        *) OS_TYPE="unknown"; OS_LABEL="Unknown" ;;
    esac
}

detect_shell_rc() {
    local shell_name
    shell_name=$(basename "$\{SHELL:-/bin/sh\}")
    case "$shell_name" in
        zsh)  SHELL_NAME="zsh";  SHELL_RC="$HOME/.zshrc" ;;
        bash) SHELL_NAME="bash"
              if [ "$OS_TYPE" = "macos" ] && [ -f "$HOME/.bash_profile" ]; then
                  SHELL_RC="$HOME/.bash_profile"
              else
                  SHELL_RC="$HOME/.bashrc"
              fi
              ;;
        fish) SHELL_NAME="fish"; SHELL_RC="$HOME/.config/fish/conf.d/${CORP_SLUG}.fish" ;;
        *)    SHELL_NAME="sh";   SHELL_RC="$HOME/.profile" ;;
    esac
    [ -f "$SHELL_RC" ] || { mkdir -p "$(dirname "$SHELL_RC")" && touch "$SHELL_RC"; }
}

# tpl: detect IDE binaries. Sets:
# tpl:   HAS_VSCODE=yes|no, HAS_JETBRAINS=yes|no, JETBRAINS_BINS="idea pycharm ..."
detect_ides() {
    HAS_VSCODE="no"
    HAS_JETBRAINS="no"
    JETBRAINS_BINS=""

    if command -v code >/dev/null 2>&1; then
        HAS_VSCODE="yes"
        VSCODE_VERSION="$(code --version 2>/dev/null | head -1 || echo unknown)"
    fi

    for bin in idea pycharm webstorm; do
        if command -v "$bin" >/dev/null 2>&1; then
            HAS_JETBRAINS="yes"
            JETBRAINS_BINS="$\{JETBRAINS_BINS\}$\{JETBRAINS_BINS:+ \}$bin"
        fi
    done
}

show_banner() {
    printf '\n$\{ORANGE\}$\{BOLD\}'
    printf '  ╔═══════════════════════════════════════════════╗\n'
    printf '  ║  %-44s ║\n' "${CORP_NAME} — installer"
    printf '  ║  %-44s ║\n' "Powered by ${CORP_POWERED_BY}"
    printf '  ╚═══════════════════════════════════════════════╝\n'
    printf '$\{RESET\}\n'
}

# tpl: ---------- markers (must stay in sync with uninstall.sh) ----------
MARKER_START="# >>> ${CORP_SLUG} >>>"
MARKER_END="# <<< ${CORP_SLUG} <<<"
GENERATED_MARKER="# ${CORP_SLUG}-managed: generated by ${CORP_NAME} launcher v${CORP_LAUNCHER_VERSION}"

# tpl: ---------- begin ----------
show_banner

step "[1/7] Detect environment"
detect_os
if [ "$OS_TYPE" = "unknown" ]; then
    fail "Unsupported OS. Supported: macOS, Linux, WSL, Git Bash."
    exit 1
fi
info "OS         : $OS_LABEL"
detect_shell_rc
info "Shell RC   : $SHELL_RC"
info "Install dir: $INSTALL_DIR"

# tpl: ---------------------------------------------------------------------
# tpl: Step 2 — IDE detection
# tpl: Continue.dev runs as an extension/plugin inside an IDE. We don't
# tpl: hard-fail if no IDE is found — the user may install one later.
# tpl: ---------------------------------------------------------------------
step "[2/7] Detect supported IDEs"
detect_ides

if [ "$HAS_VSCODE" = "yes" ]; then
    info "VS Code    : $VSCODE_VERSION"
else
    warn "VS Code 'code' command not found in PATH."
fi

if [ "$HAS_JETBRAINS" = "yes" ]; then
    info "JetBrains  : $JETBRAINS_BINS"
else
    warn "No JetBrains CLI launcher found (idea / pycharm / webstorm)."
fi

if [ "$HAS_VSCODE" = "no" ] && [ "$HAS_JETBRAINS" = "no" ]; then
    warn "No supported IDE detected. Install VS Code or a JetBrains IDE,"
    warn "then re-run '${CORP_SLUG} --install-extension' or this installer."
    warn "Continuing anyway — extension install will be skipped."
fi

# tpl: ---------------------------------------------------------------------
# tpl: Step 3 — Continue extension for VS Code
# tpl: For JetBrains we only print instructions: the plugin must be
# tpl: installed from JetBrains Marketplace inside the IDE (no CLI hook).
# tpl: ---------------------------------------------------------------------
step "[3/7] Install Continue extension"
if [ "$HAS_VSCODE" = "yes" ]; then
    if code --list-extensions 2>/dev/null | grep -qi '^Continue\.continue$'; then
        info "Continue.continue already installed in VS Code"
    else
        if ask "Install the Continue extension in VS Code now?"; then
            if code --install-extension Continue.continue --force >/dev/null 2>&1; then
                info "Installed Continue.continue"
            else
                warn "VS Code extension install failed — install manually from Marketplace"
            fi
        else
            warn "Skipped — install later with: code --install-extension Continue.continue"
        fi
    fi
else
    warn "VS Code not detected — skipping extension install."
fi

if [ "$HAS_JETBRAINS" = "yes" ]; then
    warn "JetBrains plugin must be installed from the Marketplace:"
    warn "  Settings → Plugins → search 'Continue' → Install"
fi

# tpl: ---------------------------------------------------------------------
# tpl: Step 4 — Permissions
# tpl: ---------------------------------------------------------------------
step "[4/7] Set permissions"
chmod 755 "$INSTALL_DIR/${CORP_SLUG}"
info "launcher executable: $INSTALL_DIR/${CORP_SLUG}"
if [ -d "$INSTALL_DIR/scripts" ]; then
    find "$INSTALL_DIR/scripts" -type f -name "*.sh" -exec chmod 644 {} \;
    info "shared modules: $INSTALL_DIR/scripts/"
fi
chmod 755 "$INSTALL_DIR/uninstall.sh" 2>/dev/null || true

# tpl: ---------------------------------------------------------------------
# tpl: Step 5 — managed ~/.continue/config.yaml
# tpl: render.py has already rendered $INSTALL_DIR/config.yaml from the
# tpl: template. Here we simply copy it into place, backing up any prior
# tpl: user-edited file.
# tpl: ---------------------------------------------------------------------
step "[5/7] Install ~/.continue/config.yaml"

CONTINUE_DIR="$HOME/.continue"
CONTINUE_CONF_DEST="$CONTINUE_DIR/config.yaml"
mkdir -p "$CONTINUE_DIR"
chmod 700 "$CONTINUE_DIR"

if [ -r "$INSTALL_DIR/config.yaml" ]; then
    if [ -f "$CONTINUE_CONF_DEST" ]; then
        if grep -qF "$GENERATED_MARKER" "$CONTINUE_CONF_DEST" 2>/dev/null; then
            info "Refreshing managed $CONTINUE_CONF_DEST"
        else
            warn "Existing $CONTINUE_CONF_DEST was NOT generated by ${CORP_NAME}"
            cp "$CONTINUE_CONF_DEST" "$\{CONTINUE_CONF_DEST\}.${CORP_SLUG}-backup"
            warn "  backup: $\{CONTINUE_CONF_DEST\}.${CORP_SLUG}-backup"
        fi
    fi
    install -m 0600 "$INSTALL_DIR/config.yaml" "$CONTINUE_CONF_DEST"
    info "Wrote $CONTINUE_CONF_DEST"
else
    fail "missing $INSTALL_DIR/config.yaml — installer aborted"
    exit 1
fi

# tpl: ---------------------------------------------------------------------
# tpl: Step 6 — shell RC block (idempotent)
# tpl: ---------------------------------------------------------------------
step "[6/7] Wire up the shell ($SHELL_RC)"

if grep -qF "$MARKER_START" "$SHELL_RC" 2>/dev/null; then
    cp "$SHELL_RC" "$\{SHELL_RC\}.${CORP_SLUG}.bak"
    info "Backup saved at $\{SHELL_RC\}.${CORP_SLUG}.bak"
    if [ "$OS_TYPE" = "macos" ]; then
        sed -i '' "/$MARKER_START/,/$MARKER_END/d" "$SHELL_RC"
    else
        sed -i "/$MARKER_START/,/$MARKER_END/d" "$SHELL_RC"
    fi
    info "Removed previous block"
fi

{
    printf '\n%s\n' "$MARKER_START"
    printf '# %s — Powered by %s\n' "${CORP_NAME}" "${CORP_POWERED_BY}"
    printf '# Installed on %s\n' "$(date +%Y-%m-%d)"
    printf 'export ${CORP_SLUG_UPPER}_HOME="%s"\n' "$INSTALL_DIR"
    printf '${CORP_SLUG}() { "$\{${CORP_SLUG_UPPER}_HOME\}/${CORP_SLUG}" "$@"; }\n'
    printf '%s\n' "$MARKER_END"
} >> "$SHELL_RC"
info "Shell block added"

# tpl: ---------------------------------------------------------------------
# tpl: Step 7 — API token (shared secrets-store.sh)
# tpl: ---------------------------------------------------------------------
step "[7/7] Configure API token"

export CORP_NAME="${CORP_NAME}"
export CORP_SLUG="${CORP_SLUG}"
export CORP_SLUG_UPPER="${CORP_SLUG_UPPER}"
export LLM_TOKEN_URL="${LLM_TOKEN_URL}"

# shellcheck disable=SC1091
. "$INSTALL_DIR/scripts/secrets-store.sh"

load_api_key || true
if [ -n "$\{CORP_API_KEY:-\}" ]; then
    if ask "An API token is already stored. Replace it?"; then
        prompt_for_api_key
    fi
else
    prompt_for_api_key || warn "token not configured — run '${CORP_SLUG} --set-key' later"
fi

# tpl: ---------------------------------------------------------------------
# tpl: Done — final instructions
# tpl: ---------------------------------------------------------------------
printf '\n$\{ORANGE\}$\{BOLD\}  Installation complete.$\{RESET\}\n\n'
printf '  Reload your shell : $\{GREEN\}source %s$\{RESET\}\n' "$SHELL_RC"
printf '  Config file       : $\{DIM\}%s$\{RESET\}\n' "$CONTINUE_CONF_DEST"
if [ "$HAS_VSCODE" = "yes" ]; then
    printf '  Launch VS Code    : $\{GREEN\}code .$\{RESET\}  then open the Continue side panel\n'
    printf '  Chat shortcut     : $\{DIM\}Cmd/Ctrl+L$\{RESET\}  (or type $\{GREEN\}/continue$\{RESET\} in chat)\n'
fi
if [ "$HAS_JETBRAINS" = "yes" ]; then
    printf '  JetBrains         : open IDE → Continue tool window → /continue\n'
fi
# tpl: --- Optional extras (CA bundle / skills / MCP) -----------------------
if [ "${CA_DETECT_AUTO}" = "yes" ] && [ -f "$INSTALL_DIR/scripts/extract-corp-ca.sh" ]; then
    source "$INSTALL_DIR/scripts/extract-corp-ca.sh" && extract_corp_ca || true
fi
if [ -f "$INSTALL_DIR/scripts/install-skills.sh" ]; then
    source "$INSTALL_DIR/scripts/install-skills.sh" && install_skills || true
fi
if [ -f "$INSTALL_DIR/scripts/install-mcp.sh" ]; then
    source "$INSTALL_DIR/scripts/install-mcp.sh" && install_mcp_servers || true
fi

printf '  Diagnostics       : $\{DIM\}${CORP_SLUG} --status$\{RESET\}\n'
printf '  Update            : $\{DIM\}${CORP_SLUG} --update$\{RESET\}\n'
printf '  Uninstall         : $\{DIM\}${CORP_SLUG} --uninstall$\{RESET\}\n\n'
[ "${VPN_REQUIRED}" = "yes" ] && printf '  $\{YELLOW\}[!]$\{RESET\}  Corporate VPN required before first launch.\n\n'
