#!/usr/bin/env bash
# =====================================================================
#  ${CORP_NAME} — Continue.dev launcher uninstaller
#  Powered by ${CORP_POWERED_BY}
#
#  Idempotent: safe to run multiple times.
#  - Removes the shell RC block (with backup)
#  - Stops strip-proxy if it happens to be running
#  - Deletes ~/.continue/config.yaml only if it carries our marker
#    (restores .continue/config.yaml.${CORP_SLUG}-backup if present)
#  - Removes the API token from keychain / libsecret / fallback file
#  - Optionally removes the install dir
# =====================================================================

set -euo pipefail

INSTALL_DIR="$(cd "$(dirname "$\{BASH_SOURCE[0]\}")" && pwd)"

if [ -t 1 ]; then
    RED="\033[31m"
    GREEN="\033[32m"
    YELLOW="\033[33m"
    DIM="\033[2m"
    BOLD="\033[1m"
    RESET="\033[0m"
else
    RED=""; GREEN=""; YELLOW=""; DIM=""; BOLD=""; RESET=""
fi

info() { printf '  $\{GREEN\}[OK]$\{RESET\} %s\n' "$*"; }
warn() { printf '  $\{YELLOW\}[!]$\{RESET\}  %s\n' "$*"; }
skip() { printf '  $\{DIM\}[--]$\{RESET\} %s\n' "$*"; }
fail() { printf '  $\{RED\}[KO]$\{RESET\} %s\n' "$*" >&2; }

printf '$\{BOLD\}${CORP_NAME} — Continue.dev uninstalling$\{RESET\}\n\n'

OS_TYPE="linux"
case "$(uname -s)" in
    Darwin*) OS_TYPE="macos" ;;
    MINGW*|MSYS*|CYGWIN*) OS_TYPE="gitbash" ;;
esac

# tpl: ---------- 1. detect shell RC ----------
detect_shell_rc() {
    local shell_name
    shell_name=$(basename "$\{SHELL:-/bin/sh\}")
    case "$shell_name" in
        zsh)  SHELL_RC="$HOME/.zshrc" ;;
        bash)
            if [ "$OS_TYPE" = "macos" ] && [ -f "$HOME/.bash_profile" ]; then
                SHELL_RC="$HOME/.bash_profile"
            else
                SHELL_RC="$HOME/.bashrc"
            fi
            ;;
        fish) SHELL_RC="$HOME/.config/fish/conf.d/${CORP_SLUG}.fish" ;;
        *)    SHELL_RC="$HOME/.profile" ;;
    esac
}
detect_shell_rc

# tpl: ---------- 2. remove shell RC block ----------
MARKER_START="# >>> ${CORP_SLUG} >>>"
MARKER_END="# <<< ${CORP_SLUG} <<<"
GENERATED_MARKER="# ${CORP_SLUG}-managed: generated by ${CORP_NAME} launcher"

if [ -f "$SHELL_RC" ] && grep -qF "$MARKER_START" "$SHELL_RC" 2>/dev/null; then
    cp "$SHELL_RC" "$\{SHELL_RC\}.${CORP_SLUG}.uninstall.bak"
    if [ "$OS_TYPE" = "macos" ]; then
        sed -i '' "/$MARKER_START/,/$MARKER_END/d" "$SHELL_RC"
    else
        sed -i "/$MARKER_START/,/$MARKER_END/d" "$SHELL_RC"
    fi
    info "Removed shell RC block from $SHELL_RC (backup: $\{SHELL_RC\}.${CORP_SLUG}.uninstall.bak)"
else
    skip "No shell block found in $SHELL_RC"
fi

# tpl: ---------- 3. stop strip-proxy if running ----------
# tpl: Continue.dev typically does not run a strip-proxy, but the install
# tpl: script may have started one for header sanitisation — check anyway.
PID_FILE="/tmp/${CORP_SLUG}-strip-proxy.pid"
if [ -f "$PID_FILE" ]; then
    pid=$(cat "$PID_FILE" 2>/dev/null || true)
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
        kill "$pid" 2>/dev/null || true
        info "Stopped strip-proxy (pid $pid)"
    fi
    rm -f "$PID_FILE"
fi
rm -f "/tmp/${CORP_SLUG}-strip-proxy.log" "/tmp/${CORP_SLUG}-strip-proxy.lock" 2>/dev/null || true

# tpl: ---------- 4. remove ~/.continue/config.yaml if managed ----------
CONTINUE_DIR="$HOME/.continue"
CONTINUE_CONF="$CONTINUE_DIR/config.yaml"
CONTINUE_BACKUP="$CONTINUE_DIR/config.yaml.${CORP_SLUG}-backup"

if [ -f "$CONTINUE_CONF" ]; then
    # tpl: only inspect the first line — we stamp "Managed by ${CORP_NAME}"
    # tpl: at the very top of the generated file. A hand-rolled config will
    # tpl: not have it there and must be preserved.
    first_line=$(head -n 1 "$CONTINUE_CONF" 2>/dev/null || true)
    if printf '%s' "$first_line" | grep -qF "Managed by ${CORP_NAME}"; then
        cp "$CONTINUE_CONF" "$\{CONTINUE_CONF\}.${CORP_SLUG}.uninstall.bak"
        rm -f "$CONTINUE_CONF"
        info "Removed managed $CONTINUE_CONF (backup: $\{CONTINUE_CONF\}.${CORP_SLUG}.uninstall.bak)"

        if [ -f "$CONTINUE_BACKUP" ]; then
            mv "$CONTINUE_BACKUP" "$CONTINUE_CONF"
            info "Restored pre-install $CONTINUE_CONF from $CONTINUE_BACKUP"
        fi
    else
        skip "$CONTINUE_CONF is not corporate-managed — left in place"
    fi
elif [ -f "$CONTINUE_BACKUP" ]; then
    # tpl: edge case — managed config already removed manually, but the
    # tpl: original backup still sits next to it. Put it back.
    mv "$CONTINUE_BACKUP" "$CONTINUE_CONF"
    info "Restored pre-install $CONTINUE_CONF from $CONTINUE_BACKUP"
fi

# tpl: ---------- 5. clear API token from secret stores ----------
if command -v security >/dev/null 2>&1; then
    if security delete-generic-password -s "${CORP_SLUG}" -a "$USER" >/dev/null 2>&1; then
        info "Removed macOS keychain entry for ${CORP_SLUG}"
    else
        skip "No keychain entry to remove"
    fi
fi
if command -v secret-tool >/dev/null 2>&1; then
    if secret-tool clear service "${CORP_SLUG}" username "$USER" 2>/dev/null; then
        info "Removed libsecret entry for ${CORP_SLUG}"
    else
        skip "No libsecret entry to remove"
    fi
fi

# tpl: ---------- 6. remove fallback conf file ----------
if [ -f "$HOME/.${CORP_SLUG}.conf" ]; then
    rm -f "$HOME/.${CORP_SLUG}.conf"
    info "Removed $HOME/.${CORP_SLUG}.conf"
else
    skip "No fallback $HOME/.${CORP_SLUG}.conf to remove"
fi

# tpl: ---------- 7. ask before removing install dir ----------
if [ -z "$INSTALL_DIR" ] || [ "$INSTALL_DIR" = "/" ] || [ "$INSTALL_DIR" = "$HOME" ]; then
    warn "Refusing to delete suspicious INSTALL_DIR: '$INSTALL_DIR'"
elif [ -d "$INSTALL_DIR" ]; then
    printf '  $\{YELLOW\}Remove install directory %s? [y/N]$\{RESET\} ' "$INSTALL_DIR"
    read -r ans
    case "$ans" in
        [yY]*)
            PARENT_DIR="$(dirname "$INSTALL_DIR")"
            cd "$PARENT_DIR"
            rm -rf "$INSTALL_DIR"
            info "Removed $INSTALL_DIR"
            ;;
        *)
            skip "Kept $INSTALL_DIR — remove manually if desired"
            ;;
    esac
fi

printf '\n$\{GREEN\}$\{BOLD\}Uninstall complete.$\{RESET\}\n'
printf '  Reload your shell to drop the ${CORP_SLUG} command:\n'
printf '    $\{DIM\}source %s$\{RESET\}\n\n' "$SHELL_RC"
