#!/usr/bin/env bash
# tpl: ${CORP_NAME} — Corporate launcher around Gemini CLI
# tpl: Powered by ${CORP_POWERED_BY}
# tpl: Generated by the corporate-launcher skill — do not edit by hand.
#
# tpl: This wrapper enforces:
# tpl:   - exclusive routing through the corporate AI backend (${GM_BACKEND})
# tpl:   - VPN gate, corporate proxy, custom CA bundle
# tpl:   - telemetry off, no third-party leak
# tpl:   - identity lock via ~/.gemini/GEMINI.md
# tpl:
# tpl: ANTI-PATTERN guarded against: mixing GEMINI_API_KEY with Vertex AI
# tpl: (upstream issue #5585) — we explicitly unset both API key env vars
# tpl: before exporting Vertex credentials.

set -euo pipefail

# --- Resolved at install time -------------------------------------------------
INSTALL_DIR="__INSTALL_DIR__"
CORP_NAME="${CORP_NAME}"
CORP_SLUG="${CORP_SLUG}"
CORP_SLUG_UPPER="${CORP_SLUG_UPPER}"

# --- Backend config (frozen) --------------------------------------------------
GM_BACKEND="${GM_BACKEND}"               # tpl: vertex | ai-studio
GM_PRIMARY_MODEL="${GM_PRIMARY_MODEL}"
GM_VERTEX_PROJECT="${GM_VERTEX_PROJECT}"
GM_VERTEX_LOCATION="${GM_VERTEX_LOCATION}"
GM_AUTH_MODE="${GM_AUTH_MODE}"           # tpl: ADC | api-key

# --- Network config -----------------------------------------------------------
export VPN_REQUIRED="${VPN_REQUIRED}"
export VPN_PROBE_URL="${VPN_PROBE_URL}"
export PROXY_HOST="${PROXY_HOST}"
export PROXY_PORT="${PROXY_PORT}"
export NO_PROXY_LIST="${NO_PROXY_LIST}"
export CA_BUNDLE_PATH="${CA_BUNDLE_PATH}"
export ACCEPT_TLS_INSPECTION="${ACCEPT_TLS_INSPECTION}"

# --- Source shared modules ----------------------------------------------------
# shellcheck source=/dev/null
. "$INSTALL_DIR/lib/vpn-check.sh"
# shellcheck source=/dev/null
. "$INSTALL_DIR/lib/proxy-detect.sh"
# shellcheck source=/dev/null
. "$INSTALL_DIR/lib/secrets-store.sh"

# --- Colors -------------------------------------------------------------------
ORANGE="\033[38;5;208m"
RED="\033[31m"
YELLOW="\033[33m"
DIM="\033[2m"
RESET="\033[0m"

corp_info() { printf '%b[%s]%b %s\n' "$ORANGE" "$CORP_NAME" "$RESET" "$1"; }
corp_warn() { printf '%b[%s]%b %s\n' "$YELLOW" "$CORP_NAME" "$RESET" "$1" >&2; }
corp_fail() { printf '%b[%s]%b %s\n' "$RED" "$CORP_NAME" "$RESET" "$1" >&2; }

# --- Sanity: terminal title ---------------------------------------------------
printf '\033]0;%s\007' "$CORP_NAME" 2>/dev/null || true

# --- Step 1: corporate VPN ----------------------------------------------------
check_vpn || exit 1

# --- Step 2: proxy + CA bundle ------------------------------------------------
setup_proxy
setup_ca_bundle

# --- Step 3: backend-specific env --------------------------------------------
# tpl: Hard reset of any inherited credentials to avoid auth confusion.
unset GEMINI_API_KEY GOOGLE_API_KEY GOOGLE_APPLICATION_CREDENTIALS_BLOB

case "$GM_BACKEND" in
    vertex)
        # tpl: CRITICAL — Vertex must NEVER see GEMINI_API_KEY (issue #5585)
        unset GEMINI_API_KEY GOOGLE_API_KEY

        if [ -z "$GM_VERTEX_PROJECT" ] || [ -z "$GM_VERTEX_LOCATION" ]; then
            corp_fail "Vertex backend requires GM_VERTEX_PROJECT and GM_VERTEX_LOCATION."
            exit 1
        fi

        export GOOGLE_GENAI_USE_VERTEXAI=true
        export GOOGLE_CLOUD_PROJECT="$GM_VERTEX_PROJECT"
        export GOOGLE_CLOUD_LOCATION="$GM_VERTEX_LOCATION"

        # tpl: Data-residency guardrail. gemini-3.* on a regional endpoint
        # tpl: other than `global` may not honor EU residency yet.
        if [[ "$GM_PRIMARY_MODEL" == *"gemini-3"* ]] && [ "$GM_VERTEX_LOCATION" != "global" ]; then
            corp_warn "Model $GM_PRIMARY_MODEL on location $GM_VERTEX_LOCATION may not honor EU data-residency."
            corp_warn "Consider GM_VERTEX_LOCATION=global or pin to a Gemini 2.x model."
        fi

        # tpl: Auth — Application Default Credentials are preferred (keyless).
        if [ "$GM_AUTH_MODE" = "ADC" ]; then
            if ! command -v gcloud >/dev/null 2>&1; then
                corp_fail "gcloud CLI not found — required for ADC auth."
                exit 1
            fi
            # tpl: Quick sanity check that ADC is set up
            if ! gcloud auth application-default print-access-token >/dev/null 2>&1; then
                corp_warn "No active ADC session. Run: gcloud auth application-default login"
            fi
        else
            # tpl: Service-account key file mode
            if [ -n "${GOOGLE_APPLICATION_CREDENTIALS:-}" ] && [ ! -r "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
                corp_fail "GOOGLE_APPLICATION_CREDENTIALS is set but the file is not readable."
                exit 1
            fi
        fi
        ;;

    ai-studio)
        # tpl: API-key mode — explicitly forbid any Vertex flag.
        unset GOOGLE_GENAI_USE_VERTEXAI GOOGLE_CLOUD_PROJECT GOOGLE_CLOUD_LOCATION

        if ! load_api_key; then
            corp_fail "Could not load corporate API key from the secret store."
            exit 1
        fi
        if [ -z "${CORP_API_KEY:-}" ]; then
            prompt_for_api_key || exit 1
        fi
        export GEMINI_API_KEY="$CORP_API_KEY"
        ;;

    *)
        corp_fail "Unknown backend: $GM_BACKEND (expected: vertex | ai-studio)"
        exit 1
        ;;
esac

# --- Step 4: telemetry + privacy hard-off ------------------------------------
export GEMINI_TELEMETRY_ENABLED=false
export DO_NOT_TRACK=1
export DISABLE_AUTOUPDATER=1

# --- Step 5: identity injection ----------------------------------------------
# tpl: Gemini CLI loads ~/.gemini/GEMINI.md hierarchically. We pin our copy
# tpl: at the home level so it always applies.
export GEMINI_SYSTEM_MD="$HOME/.gemini/GEMINI.md"
export GEMINI_MODEL="$GM_PRIMARY_MODEL"

# --- Step 6: hand off to the real binary -------------------------------------
if ! command -v gemini >/dev/null 2>&1; then
    corp_fail "Underlying CLI engine not found. Reinstall via: $INSTALL_DIR/install.sh"
    exit 127
fi

corp_info "Backend: $GM_BACKEND | Model: $GM_PRIMARY_MODEL"
[ "$GM_BACKEND" = "vertex" ] && corp_info "Project: $GM_VERTEX_PROJECT | Region: $GM_VERTEX_LOCATION"
printf '\n  %sProudly made from France with %s❤️%s\n' "$DIM" "$RED" "$RESET"

exec gemini "$@"
