# tpl: ${CORP_NAME} - Corporate launcher around Gemini CLI (PowerShell 7+)
# tpl: Powered by ${CORP_POWERED_BY}
# tpl: Generated by the corporate-launcher skill - do not edit by hand.
#
# tpl: This wrapper enforces:
# tpl:   - exclusive routing through the corporate AI backend (${GM_BACKEND})
# tpl:   - VPN gate, corporate proxy, custom CA bundle
# tpl:   - telemetry off, no third-party leak
# tpl:   - identity lock via ~/.gemini/GEMINI.md
# tpl:
# tpl: ANTI-PATTERN guarded against: mixing GEMINI_API_KEY with Vertex AI
# tpl: (upstream issue #5585) - we explicitly Remove-Item both API key env
# tpl: vars before exporting Vertex credentials.

#Requires -Version 7.0
[CmdletBinding()]
param(
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$Args
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# --- Resolved at install time ------------------------------------------------
$InstallDir       = '__INSTALL_DIR__'
$CorpName         = '${CORP_NAME}'
$CorpSlug         = '${CORP_SLUG}'
$CorpSlugUpper    = '${CORP_SLUG_UPPER}'
$CorpPoweredBy    = '${CORP_POWERED_BY}'

# --- Backend config (frozen) -------------------------------------------------
$GmBackend         = '${GM_BACKEND}'           # tpl: vertex | ai-studio
$GmPrimaryModel    = '${GM_PRIMARY_MODEL}'
$GmVertexProject   = '${GM_VERTEX_PROJECT}'
$GmVertexLocation  = '${GM_VERTEX_LOCATION}'
$GmAuthMode        = '${GM_AUTH_MODE}'         # tpl: ADC | api-key

# --- Network config (exported for shared modules) ----------------------------
$env:VPN_REQUIRED          = '${VPN_REQUIRED}'
$env:VPN_PROBE_URL         = '${VPN_PROBE_URL}'
$env:PROXY_HOST            = '${PROXY_HOST}'
$env:PROXY_PORT            = '${PROXY_PORT}'
$env:NO_PROXY_LIST         = '${NO_PROXY_LIST}'
$env:CA_BUNDLE_PATH        = '${CA_BUNDLE_PATH}'
$env:ACCEPT_TLS_INSPECTION = '${ACCEPT_TLS_INSPECTION}'
$env:CORP_NAME             = $CorpName
$env:CORP_SLUG             = $CorpSlug
$env:CORP_SLUG_UPPER       = $CorpSlugUpper
$env:LLM_TOKEN_URL         = '${LLM_TOKEN_URL}'

# --- Source shared modules ---------------------------------------------------
. (Join-Path $InstallDir 'lib/vpn-check.ps1')
. (Join-Path $InstallDir 'lib/proxy-detect.ps1')
. (Join-Path $InstallDir 'lib/secrets-store.ps1')

# --- Colors / helpers --------------------------------------------------------
function Corp-Info { param([string]$Msg) Write-Host "[$CorpName] $Msg" -ForegroundColor DarkYellow }
function Corp-Warn { param([string]$Msg) Write-Host "[$CorpName] $Msg" -ForegroundColor Yellow }
function Corp-Fail { param([string]$Msg) Write-Host "[$CorpName] $Msg" -ForegroundColor Red }

# --- Sanity: terminal title --------------------------------------------------
try { $Host.UI.RawUI.WindowTitle = $CorpName } catch { }

# --- Flags -------------------------------------------------------------------
function Show-Help {
    @"
$CorpName - Corporate AI CLI (Powered by $CorpPoweredBy)

Usage:
  $CorpSlug [gemini args...]
  $CorpSlug --help        Show this help
  $CorpSlug --version     Show wrapper + engine version
  $CorpSlug --status      Show backend, proxy, VPN status
  $CorpSlug --set-key     (Re)store the API key in the OS secret store (ai-studio only)
  $CorpSlug --uninstall   Run the uninstaller

Backend:  $GmBackend
Model:    $GmPrimaryModel
Install:  $InstallDir
"@ | Write-Host
}

function Show-Version {
    Write-Host "$CorpName wrapper - Powered by $CorpPoweredBy"
    if (Get-Command gemini -ErrorAction SilentlyContinue) {
        $v = (& gemini --version 2>$null) -join ' '
        Write-Host "Engine: $v"
    } else {
        Write-Host 'Engine: not installed'
    }
}

function Show-Status {
    Write-Host "Backend:        $GmBackend"
    Write-Host "Model:          $GmPrimaryModel"
    if ($GmBackend -eq 'vertex') {
        Write-Host "Project:        $GmVertexProject"
        Write-Host "Location:       $GmVertexLocation"
        Write-Host "Auth mode:      $GmAuthMode"
    }
    Write-Host "VPN required:   $env:VPN_REQUIRED"
    Write-Host "Proxy host:     $env:PROXY_HOST`:$env:PROXY_PORT"
    Write-Host "CA bundle:      $env:CA_BUNDLE_PATH"
    Write-Host "Install dir:    $InstallDir"
}

if ($Args -and $Args.Count -gt 0) {
    switch ($Args[0]) {
        '--help'      { Show-Help;    exit 0 }
        '-h'          { Show-Help;    exit 0 }
        '--version'   { Show-Version; exit 0 }
        '--status'    { Show-Status;  exit 0 }
        '--set-key'   {
            if ($GmBackend -ne 'ai-studio') {
                Corp-Fail '--set-key only applies to ai-studio backend.'
                exit 1
            }
            Prompt-ForApiKey | Out-Null
            exit 0
        }
        '--uninstall' {
            $uninstaller = Join-Path $InstallDir 'uninstall.ps1'
            if (Test-Path $uninstaller) { & $uninstaller; exit $LASTEXITCODE }
            Corp-Fail "Uninstaller not found at $uninstaller"
            exit 1
        }
    }
}

# --- Step 1: corporate VPN ---------------------------------------------------
if (-not (Check-Vpn)) { exit 1 }

# --- Step 2: proxy + CA bundle -----------------------------------------------
Setup-Proxy
Setup-CaBundle

# --- Step 3: backend-specific env --------------------------------------------
# tpl: Hard reset of any inherited credentials to avoid auth confusion.
Remove-Item Env:GEMINI_API_KEY                       -ErrorAction Ignore
Remove-Item Env:GOOGLE_API_KEY                       -ErrorAction Ignore
Remove-Item Env:GOOGLE_APPLICATION_CREDENTIALS_BLOB  -ErrorAction Ignore

switch ($GmBackend) {
    'vertex' {
        # tpl: CRITICAL - Vertex must NEVER see GEMINI_API_KEY (issue #5585)
        Remove-Item Env:GEMINI_API_KEY -ErrorAction Ignore
        Remove-Item Env:GOOGLE_API_KEY -ErrorAction Ignore

        if ([string]::IsNullOrEmpty($GmVertexProject) -or [string]::IsNullOrEmpty($GmVertexLocation)) {
            Corp-Fail 'Vertex backend requires GM_VERTEX_PROJECT and GM_VERTEX_LOCATION.'
            exit 1
        }

        $env:GOOGLE_GENAI_USE_VERTEXAI = 'true'
        $env:GOOGLE_CLOUD_PROJECT      = $GmVertexProject
        $env:GOOGLE_CLOUD_LOCATION     = $GmVertexLocation

        # tpl: Data-residency guardrail. gemini-3.* on a regional endpoint
        # tpl: other than `global` may not honor EU residency yet.
        if ($GmPrimaryModel -like '*gemini-3*' -and $GmVertexLocation -ne 'global') {
            Corp-Warn "Model $GmPrimaryModel on location $GmVertexLocation may not honor EU data-residency."
            Corp-Warn 'Consider GM_VERTEX_LOCATION=global or pin to a Gemini 2.x model.'
        }

        # tpl: Auth - Application Default Credentials are preferred (keyless).
        if ($GmAuthMode -eq 'ADC') {
            if (-not (Get-Command gcloud -ErrorAction SilentlyContinue)) {
                Corp-Fail 'gcloud CLI not found - required for ADC auth.'
                exit 1
            }
            # tpl: Quick sanity check that ADC is set up
            $null = & gcloud auth application-default print-access-token 2>$null
            if ($LASTEXITCODE -ne 0) {
                Corp-Warn 'No active ADC session. Run: gcloud auth application-default login'
                $answer = Read-Host 'Run it now? [y/N]'
                if ($answer -match '^[yY]') {
                    & gcloud auth application-default login
                    if ($LASTEXITCODE -ne 0) {
                        Corp-Fail 'ADC login failed.'
                        exit 1
                    }
                }
            }
        } else {
            # tpl: Service-account key file mode
            if ($env:GOOGLE_APPLICATION_CREDENTIALS -and -not (Test-Path $env:GOOGLE_APPLICATION_CREDENTIALS)) {
                Corp-Fail 'GOOGLE_APPLICATION_CREDENTIALS is set but the file is not readable.'
                exit 1
            }
        }
    }

    'ai-studio' {
        # tpl: API-key mode - explicitly forbid any Vertex flag.
        Remove-Item Env:GOOGLE_GENAI_USE_VERTEXAI -ErrorAction Ignore
        Remove-Item Env:GOOGLE_CLOUD_PROJECT      -ErrorAction Ignore
        Remove-Item Env:GOOGLE_CLOUD_LOCATION     -ErrorAction Ignore

        if (-not (Load-ApiKey)) {
            Corp-Fail 'Could not load corporate API key from the secret store.'
            exit 1
        }
        if ([string]::IsNullOrEmpty($script:CorpApiKey)) {
            if (-not (Prompt-ForApiKey)) { exit 1 }
        }
        $env:GEMINI_API_KEY = $script:CorpApiKey
    }

    default {
        Corp-Fail "Unknown backend: $GmBackend (expected: vertex | ai-studio)"
        exit 1
    }
}

# --- Step 4: telemetry + privacy hard-off ------------------------------------
$env:GEMINI_TELEMETRY_ENABLED = 'false'
$env:DO_NOT_TRACK             = '1'
$env:DISABLE_AUTOUPDATER      = '1'

# --- Step 5: identity injection ----------------------------------------------
# tpl: Gemini CLI loads ~/.gemini/GEMINI.md hierarchically. We pin our copy
# tpl: at the home level so it always applies.
$GeminiHome = Join-Path $HOME '.gemini'
if (-not (Test-Path $GeminiHome)) {
    New-Item -ItemType Directory -Path $GeminiHome -Force | Out-Null
}

$GeminiMdSrc = Join-Path $InstallDir 'share/GEMINI.md'
$GeminiMdDst = Join-Path $GeminiHome 'GEMINI.md'
if ((Test-Path $GeminiMdSrc) -and -not (Test-Path $GeminiMdDst)) {
    Copy-Item -Path $GeminiMdSrc -Destination $GeminiMdDst -Force
}

$env:GEMINI_SYSTEM_MD = $GeminiMdDst
$env:GEMINI_MODEL     = $GmPrimaryModel

# --- Step 6: hand off to the real binary -------------------------------------
if (-not (Get-Command gemini -ErrorAction SilentlyContinue)) {
    Corp-Fail "Underlying CLI engine not found. Reinstall via: $InstallDir/install.ps1"
    exit 127
}

Corp-Info "Backend: $GmBackend | Model: $GmPrimaryModel"
if ($GmBackend -eq 'vertex') {
    Corp-Info "Project: $GmVertexProject | Region: $GmVertexLocation"
}

# tpl: PowerShell has no `exec`. We invoke and propagate the exit code.
if ($Args) {
    & gemini @Args
} else {
    & gemini
}
exit $LASTEXITCODE
