{
  "$schema": "https://raw.githubusercontent.com/google-gemini/gemini-cli/main/packages/cli/src/config/settingsSchema.json",
  "_comment": "${CORP_NAME} corporate Gemini CLI settings. Powered by ${CORP_POWERED_BY}. Generated by the corporate-launcher skill — do not edit by hand.",

  "model": {
    "default": "${GM_PRIMARY_MODEL}"
  },

  "security": {
    "auth": {
      "enforcedType": "${GM_AUTH_ENFORCED_TYPE}",
      "selectedType": "${GM_AUTH_ENFORCED_TYPE}"
    },
    "folderTrust": {
      "enabled": true
    },
    "disableYoloMode": true,
    "environmentVariableRedaction": {
      "enabled": true,
      "blocked": [
        "*_KEY",
        "*_TOKEN",
        "*_SECRET",
        "*_PASSWORD",
        "GEMINI_API_KEY",
        "GOOGLE_API_KEY",
        "GOOGLE_APPLICATION_CREDENTIALS",
        "AWS_SECRET_ACCESS_KEY",
        "AZURE_OPENAI_API_KEY"
      ]
    }
  },

  "tools": {
    "sandbox": "${GM_SANDBOX_MODE}",
    "exclude": ${GM_TOOLS_EXCLUDE_JSON}
  },

  "mcp": {
    "allowed": []
  },
  "mcpServers": {},

  "telemetry": {
    "enabled": false,
    "logPrompts": false
  },

  "privacy": {
    "usageStatisticsEnabled": false
  },

  "admin": {
    "secureModeEnabled": true,
    "extensions": {
      "enabled": false
    }
  },

  "ui": {
    "footer": {
      "hideCWD": false,
      "hideSandboxStatus": false,
      "hideModelInfo": false
    },
    "customWitticisms": [
      "${CORP_NAME} — Powered by ${CORP_POWERED_BY}",
      "Corporate AI — stays inside the perimeter."
    ]
  },

  "advanced": {
    "autoConfigureMemory": false
  }
}
