# ${CORP_SLUG}-managed: generated by ${CORP_NAME} launcher v${CORP_LAUNCHER_VERSION}
# ${CORP_NAME} — Codex CLI configuration
# Powered by ${CORP_POWERED_BY}
#
# This file is rewritten by the launcher installer. If you need to override
# a value for a one-off run, prefer CLI flags or env vars; do not hand-edit
# this file — your changes will be overwritten on the next install/update.
#
# tpl: Codex CLI reads this from $CODEX_HOME/config.toml (default ~/.codex/).
# tpl: ${CX_BACKEND} determines whether wire_api is "responses" (Azure / OpenAI)
# tpl: or "chat" (legacy OpenAI-compatible gateways like LiteLLM).

# tpl: ---------------------------------------------------------------------
# tpl: Top-level model selection
# tpl: ---------------------------------------------------------------------
model = "${CX_PRIMARY_MODEL}"
model_provider = "${CX_PROVIDER_ID}"
model_reasoning_effort = "${CX_REASONING_EFFORT}"

# tpl: ---------------------------------------------------------------------
# tpl: Analytics / telemetry / history — all off
# tpl: These are mirrored by env vars in the launcher; the config file is the
# tpl: persistent line of defense in case the env vars are stripped by a
# tpl: child process.
# tpl: ---------------------------------------------------------------------
disable_response_storage = true
hide_agent_reasoning = false

[tui]
disable_mouse_capture = false

[history]
persistence = "none"

[telemetry]
enabled = false

[analytics]
enabled = false

[feedback]
enabled = false

[updates]
auto_check = false

# tpl: ---------------------------------------------------------------------
# tpl: Sandbox & approval defaults (overridable by requirements.toml when
# tpl: lockdown is on)
# tpl: ---------------------------------------------------------------------
approval_policy = "${CX_APPROVAL_POLICY}"
sandbox_mode = "${CX_SANDBOX_MODE}"

[sandbox_workspace_write]
network_access = false
exclude_tmpdir_env_var = true
exclude_slash_tmp = true

# tpl: ---------------------------------------------------------------------
# tpl: Model provider block
# tpl: For Azure OpenAI: base_url ends with "/openai/v1" (no api-version
# tpl: query) and wire_api must be "responses".
# tpl: For OpenAI-compatible (LiteLLM, vLLM, on-prem): wire_api = "chat".
# tpl: ---------------------------------------------------------------------
[model_providers.${CX_PROVIDER_ID}]
name = "${CORP_NAME} gateway (${CX_BACKEND})"
base_url = "${CX_PRIMARY_URL}"
env_key = "${CX_AUTH_ENV_KEY}"
wire_api = "${CX_WIRE_API}"
request_max_retries = 2
stream_idle_timeout_ms = 120000

# tpl: ---------------------------------------------------------------------
# tpl: MCP servers — empty by default. The corporate cyber baseline forbids
# tpl: arbitrary local MCP servers. If your tenant approves specific servers,
# tpl: add them here AND mirror the allowlist in requirements.toml.
# tpl: ---------------------------------------------------------------------
# [mcp_servers.example]
# command = "/path/to/server"
# args = []
# env = {}

# tpl: ---------------------------------------------------------------------
# tpl: Profiles — convenience presets the user can invoke with `codex -p <name>`
# tpl: ---------------------------------------------------------------------
[profiles.default]
model = "${CX_PRIMARY_MODEL}"
model_provider = "${CX_PROVIDER_ID}"

[profiles.fast]
model = "${CX_FAST_MODEL}"
model_provider = "${CX_PROVIDER_ID}"
model_reasoning_effort = "low"
