#!/usr/bin/env bash
# =============================================================================
# ${CORP_NAME} — Codex CLI launcher installer
# Powered by ${CORP_POWERED_BY}
#
# Idempotent. Re-runnable. Backs up the shell RC before modifying it.
# Refuses to chmod 777, modify /etc/hosts, or disable global SSL verification.
# =============================================================================

set -euo pipefail

INSTALL_DIR="$(cd "$(dirname "$\{BASH_SOURCE[0]\}")" && pwd)"
LAUNCHER_VERSION="${CORP_LAUNCHER_VERSION}"

# tpl: ---------------------------------------------------------------------
# tpl: Colors — TTY only
# tpl: ---------------------------------------------------------------------
if [ -t 1 ]; then
    C_BRAND="\033[1;38;5;${CORP_BRAND_ANSI}m"
    C_GREEN="\033[0;32m"
    C_RED="\033[0;31m"
    C_YELLOW="\033[0;33m"
    C_BOLD="\033[1m"
    C_DIM="\033[2m"
    C_RESET="\033[0m"
else
    C_BRAND=""; C_GREEN=""; C_RED=""; C_YELLOW=""; C_BOLD=""; C_DIM=""; C_RESET=""
fi

info() { printf "  ${C_GREEN}[OK]${C_RESET} %s\n" "$1"; }
warn() { printf "  ${C_YELLOW}[!!]${C_RESET} %s\n" "$1"; }
fail() { printf "  ${C_RED}[KO]${C_RESET} %s\n" "$1" >&2; }
step() { printf "\n${C_BOLD}%s${C_RESET}\n" "$1"; }

# tpl: ---------------------------------------------------------------------
# tpl: Detect OS
# tpl: ---------------------------------------------------------------------
detect_os() {
    OS_TYPE="unknown"
    case "$(uname -s)" in
        Darwin*) OS_TYPE="macos" ;;
        Linux*)
            if grep -qi microsoft /proc/version 2>/dev/null; then
                OS_TYPE="wsl"
            else
                OS_TYPE="linux"
            fi
            ;;
        MINGW*|MSYS*|CYGWIN*) OS_TYPE="gitbash" ;;
    esac
}

# tpl: ---------------------------------------------------------------------
# tpl: Detect shell + RC file
# tpl: ---------------------------------------------------------------------
detect_shell_rc() {
    local current_shell
    current_shell="$(basename "$\{SHELL:-/bin/sh\}")"
    case "$current_shell" in
        zsh)
            SHELL_NAME="zsh"
            SHELL_RC="$HOME/.zshrc"
            ;;
        bash)
            SHELL_NAME="bash"
            if [ "$OS_TYPE" = "macos" ] && [ -f "$HOME/.bash_profile" ]; then
                SHELL_RC="$HOME/.bash_profile"
            else
                SHELL_RC="$HOME/.bashrc"
            fi
            ;;
        *)
            SHELL_NAME="sh"
            SHELL_RC="$HOME/.profile"
            ;;
    esac
    [ -f "$SHELL_RC" ] || touch "$SHELL_RC"
}

# tpl: ---------------------------------------------------------------------
# tpl: Markers — used by both install + uninstall (must stay in sync)
# tpl: ---------------------------------------------------------------------
MARKER_START="# >>> ${CORP_SLUG} >>>"
MARKER_END="# <<< ${CORP_SLUG} <<<"
GENERATED_MARKER="# ${CORP_SLUG}-managed: generated by ${CORP_NAME} launcher v${CORP_LAUNCHER_VERSION}"

# tpl: ---------------------------------------------------------------------
# tpl: Banner
# tpl: ---------------------------------------------------------------------
printf "\n${C_BRAND}%s${C_RESET} ${C_DIM}— launcher installer v%s${C_RESET}\n" \
    "${CORP_NAME}" "$LAUNCHER_VERSION"
printf "${C_DIM}powered by %s${C_RESET}\n" "${CORP_POWERED_BY}"

# tpl: ---------------------------------------------------------------------
# tpl: Step 1 — OS + shell
# tpl: ---------------------------------------------------------------------
step "[1/6] Detecting environment..."
detect_os
if [ "$OS_TYPE" = "unknown" ]; then
    fail "Unsupported OS. Supported: macOS, Linux, WSL, Git Bash."
    exit 1
fi
info "os    : $OS_TYPE"
detect_shell_rc
info "shell : $SHELL_NAME ($SHELL_RC)"
info "dir   : $INSTALL_DIR"

# tpl: ---------------------------------------------------------------------
# tpl: Step 2 — Node + codex prerequisites
# tpl: Codex CLI is published to npm. If absent and the user has npm, offer
# tpl: to install it; otherwise fail with guidance (no curl|bash).
# tpl: ---------------------------------------------------------------------
step "[2/6] Checking prerequisites..."

if ! command -v node >/dev/null 2>&1; then
    fail "node is required but not installed."
    fail "Install Node.js ${CX_NODE_MIN_VERSION}+ via your corporate package manager."
    exit 1
fi
info "node  : $(node --version)"

if ! command -v npm >/dev/null 2>&1; then
    fail "npm is required but not installed."
    exit 1
fi
info "npm   : v$(npm --version)"

if ! command -v codex >/dev/null 2>&1; then
    warn "codex binary not found in PATH."
    printf "  Install Codex CLI globally via npm? [Y/n] "
    read -r answer
    case "$answer" in
        [nN]*)
            fail "codex is required to use the launcher."
            exit 1
            ;;
        *)
            info "Installing @openai/codex..."
            npm install -g @openai/codex || {
                fail "npm install failed. Check your npm registry / proxy config."
                exit 1
            }
            ;;
    esac
fi
info "codex : $(codex --version 2>/dev/null || echo 'installed')"

# tpl: ---------------------------------------------------------------------
# tpl: Step 3 — file permissions on launcher + scripts
# tpl: We use 755 on executables, 644 on configs, 600 on secrets.
# tpl: NEVER 777.
# tpl: ---------------------------------------------------------------------
step "[3/6] Setting permissions..."

chmod 755 "$INSTALL_DIR/${CORP_SLUG}"
info "launcher executable: $INSTALL_DIR/${CORP_SLUG}"

if [ -d "$INSTALL_DIR/scripts" ]; then
    find "$INSTALL_DIR/scripts" -type f -name "*.sh" -exec chmod 644 {} \;
    info "shared modules: $INSTALL_DIR/scripts/"
fi

chmod 755 "$INSTALL_DIR/uninstall.sh" 2>/dev/null || true

# tpl: ---------------------------------------------------------------------
# tpl: Step 4 — shell RC block (idempotent: backup, strip old, append new)
# tpl: ---------------------------------------------------------------------
step "[4/6] Configuring shell ($SHELL_RC)..."

# tpl: build the block in a heredoc so we don't worry about expansion order
SHELL_BLOCK="$(cat <<EOF_BLOCK
${MARKER_START}
# ${CORP_NAME} — installed $(date +%Y-%m-%d)
# install_dir: ${INSTALL_DIR}
${CORP_SLUG}() {
    "${INSTALL_DIR}/${CORP_SLUG}" "\$@"
}
export ${CORP_SLUG_UPPER}_HOME="${INSTALL_DIR}"
${MARKER_END}
EOF_BLOCK
)"

if grep -qF "$MARKER_START" "$SHELL_RC" 2>/dev/null; then
    warn "previous install detected — refreshing block"
    cp "$SHELL_RC" "${SHELL_RC}.bak"
    info "backup: ${SHELL_RC}.bak"
    if [ "$OS_TYPE" = "macos" ]; then
        sed -i '' "/$\{MARKER_START\}/,/$\{MARKER_END\}/d" "$SHELL_RC"
    else
        sed -i "/$\{MARKER_START\}/,/$\{MARKER_END\}/d" "$SHELL_RC"
    fi
fi

{
    printf "\n"
    printf "%s\n" "$SHELL_BLOCK"
} >> "$SHELL_RC"
info "block appended"

# tpl: ---------------------------------------------------------------------
# tpl: Step 5 — API token (via shared secrets-store)
# tpl: ---------------------------------------------------------------------
step "[5/6] API token..."

export CORP_NAME="${CORP_NAME}"
export CORP_SLUG="${CORP_SLUG}"
export CORP_SLUG_UPPER="${CORP_SLUG_UPPER}"
export LLM_TOKEN_URL="${LLM_TOKEN_URL}"

# shellcheck disable=SC1091
. "$INSTALL_DIR/scripts/secrets-store.sh"

load_api_key || true
if [ -n "$\{CORP_API_KEY:-\}" ]; then
    info "token already stored; use \`${CORP_SLUG} --set-key\` to rotate"
else
    prompt_for_api_key || warn "token not configured — run \`${CORP_SLUG} --set-key\` later"
fi

# tpl: ---------------------------------------------------------------------
# tpl: Step 6 — drop ~/.codex/config.toml (+ AGENTS.md, requirements.toml)
# tpl: We mark every file we generate with GENERATED_MARKER so the uninstall
# tpl: knows what was authored by this launcher (vs. pre-existing user files).
# tpl: ---------------------------------------------------------------------
step "[6/6] Writing Codex config..."

CODEX_HOME="$\{CODEX_HOME:-$HOME/.codex\}"
mkdir -p "$CODEX_HOME"

CONFIG_DEST="$CODEX_HOME/config.toml"
AGENTS_DEST="$CODEX_HOME/AGENTS.md"
REQS_DEST="$CODEX_HOME/requirements.toml"

write_if_safe() {
    local dest="$1" src="$2" label="$3"
    if [ -f "$dest" ]; then
        if grep -qF "$GENERATED_MARKER" "$dest" 2>/dev/null; then
            info "$label: refreshing managed file"
        else
            warn "$label exists and was NOT generated by ${CORP_NAME}"
            warn "  backing up to: ${dest}.bak"
            cp "$dest" "${dest}.bak"
        fi
    fi
    install -m 0644 "$src" "$dest"
}

# tpl: config.toml is mandatory
if [ -r "$INSTALL_DIR/config.toml" ]; then
    write_if_safe "$CONFIG_DEST" "$INSTALL_DIR/config.toml" "config.toml"
    info "config: $CONFIG_DEST"
else
    fail "missing $INSTALL_DIR/config.toml — installer aborted"
    exit 1
fi

# tpl: AGENTS.md is the white-label system identity (Codex equivalent of CLAUDE.md)
if [ -r "$INSTALL_DIR/BRANDING.md" ]; then
    write_if_safe "$AGENTS_DEST" "$INSTALL_DIR/BRANDING.md" "AGENTS.md"
    info "agents: $AGENTS_DEST"
fi

# tpl: requirements.toml only if admin lockdown is requested
if [ "${CX_REQUIRE_LOCKDOWN}" = "yes" ]; then
    if [ -r "$INSTALL_DIR/requirements.toml" ]; then
        write_if_safe "$REQS_DEST" "$INSTALL_DIR/requirements.toml" "requirements.toml"
        # tpl: lockdown file is read-only for the user — must not be edited
        chmod 0444 "$REQS_DEST"
        info "lockdown: $REQS_DEST (read-only)"
    else
        warn "lockdown requested but $INSTALL_DIR/requirements.toml missing"
    fi
else
    info "lockdown: disabled by tenant config"
fi

# tpl: ---------------------------------------------------------------------
# tpl: Final summary
# tpl: ---------------------------------------------------------------------
printf "\n${C_BRAND}%s${C_RESET}\n" "Installation complete."
printf "\n  ${C_BOLD}Next steps:${C_RESET}\n"
printf "    1. Reload your shell:  ${C_GREEN}source %s${C_RESET}\n" "$SHELL_RC"
if [ "${VPN_REQUIRED}" = "yes" ]; then
    printf "    2. Connect to the corporate VPN.\n"
    printf "    3. Launch:             ${C_GREEN}%s${C_RESET}\n" "${CORP_SLUG}"
else
    printf "    2. Launch:             ${C_GREEN}%s${C_RESET}\n" "${CORP_SLUG}"
fi
printf "\n  ${C_BOLD}Commands:${C_RESET}\n"
printf "    %s                  start interactive session\n" "${CORP_SLUG}"
printf "    %s --status         show resolved env (no secret)\n" "${CORP_SLUG}"
printf "    %s --set-key        rotate the API token\n" "${CORP_SLUG}"
printf "    %s --help           full help\n" "${CORP_SLUG}"
printf "\n  ${C_BOLD}Uninstall:${C_RESET}\n"
printf "    ${C_DIM}%s${C_RESET}\n\n" "$INSTALL_DIR/uninstall.sh"
