#Requires -Version 7.0
# =============================================================================
# ${CORP_NAME} - Codex CLI launcher installer (Windows / PowerShell 7+)
# Powered by ${CORP_POWERED_BY}
#
# Idempotent. Re-runnable. Backs up the PowerShell profile before modifying it.
# Refuses to weaken global ACLs or disable SSL verification system-wide.
# =============================================================================

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$InstallDir      = $PSScriptRoot
$LauncherVersion = '${CORP_LAUNCHER_VERSION}'

# tpl: ---------------------------------------------------------------------
# tpl: Colors - only when stdout is a real terminal
# tpl: ---------------------------------------------------------------------
$script:UseColor = ([Environment]::UserInteractive -and -not [Console]::IsOutputRedirected)

function Write-Info { param([string]$Msg)
    if ($script:UseColor) { Write-Host "  [OK] $Msg" -ForegroundColor Green } else { Write-Host "  [OK] $Msg" }
}
function Write-Warn { param([string]$Msg)
    if ($script:UseColor) { Write-Host "  [!!] $Msg" -ForegroundColor Yellow } else { Write-Host "  [!!] $Msg" }
}
function Write-Fail { param([string]$Msg)
    if ($script:UseColor) { Write-Host "  [KO] $Msg" -ForegroundColor Red } else { Write-Host "  [KO] $Msg" }
}
function Write-Step { param([string]$Msg)
    Write-Host ''
    if ($script:UseColor) { Write-Host $Msg -ForegroundColor White } else { Write-Host $Msg }
}

# tpl: ---------------------------------------------------------------------
# tpl: Detect PowerShell 7+
# tpl: ---------------------------------------------------------------------
function Test-PowerShell7Plus {
    if ($PSVersionTable.PSVersion.Major -lt 7) {
        Write-Fail ("PowerShell 7+ is required. Current: {0}" -f $PSVersionTable.PSVersion)
        Write-Fail 'Install PowerShell 7 via your corporate package manager (winget / MSI).'
        return $false
    }
    return $true
}

# tpl: ---------------------------------------------------------------------
# tpl: Markers - used by both install + uninstall (must stay in sync)
# tpl: ---------------------------------------------------------------------
$MarkerStart      = '# >>> ${CORP_SLUG} >>>'
$MarkerEnd        = '# <<< ${CORP_SLUG} <<<'
$GeneratedMarker  = '# ${CORP_SLUG}-managed: generated by ${CORP_NAME} launcher v${CORP_LAUNCHER_VERSION}'

# tpl: ---------------------------------------------------------------------
# tpl: Banner
# tpl: ---------------------------------------------------------------------
Write-Host ''
if ($script:UseColor) {
    Write-Host ("{0} - launcher installer v{1}" -f '${CORP_NAME}', $LauncherVersion) -ForegroundColor Cyan
    Write-Host ("powered by {0}" -f '${CORP_POWERED_BY}') -ForegroundColor DarkGray
} else {
    Write-Host ("${CORP_NAME} - launcher installer v{0}" -f $LauncherVersion)
    Write-Host 'powered by ${CORP_POWERED_BY}'
}

# tpl: ---------------------------------------------------------------------
# tpl: Step 1 - environment detection
# tpl: ---------------------------------------------------------------------
Write-Step '[1/6] Detecting environment...'

if (-not (Test-PowerShell7Plus)) { exit 1 }
Write-Info ("pwsh  : {0}" -f $PSVersionTable.PSVersion)

$OsLabel = if ($IsWindows) { 'windows' } elseif ($IsMacOS) { 'macos' } elseif ($IsLinux) { 'linux' } else { 'unknown' }
Write-Info ("os    : {0}" -f $OsLabel)

if (-not $PROFILE) {
    Write-Fail 'PowerShell $PROFILE path is empty - cannot configure profile.'
    exit 1
}
$ProfilePath = $PROFILE.CurrentUserAllHosts
if (-not (Test-Path -LiteralPath $ProfilePath -PathType Leaf)) {
    $profileDir = Split-Path -Parent $ProfilePath
    if (-not (Test-Path -LiteralPath $profileDir -PathType Container)) {
        New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
    }
    New-Item -ItemType File -Path $ProfilePath -Force | Out-Null
}
Write-Info ("profile: {0}" -f $ProfilePath)
Write-Info ("dir   : {0}" -f $InstallDir)

# tpl: ---------------------------------------------------------------------
# tpl: Step 2 - Node + codex prerequisites
# tpl: Codex CLI is published to npm. If absent and the user has npm, offer
# tpl: to install it; otherwise fail with guidance (no curl|iex).
# tpl: ---------------------------------------------------------------------
Write-Step '[2/6] Checking prerequisites...'

$nodeCmd = Get-Command node -ErrorAction SilentlyContinue
if (-not $nodeCmd) {
    Write-Fail 'node is required but not installed.'
    Write-Fail 'Install Node.js ${CX_NODE_MIN_VERSION}+ via your corporate package manager (winget).'
    exit 1
}
Write-Info ("node  : {0}" -f (& $nodeCmd.Source --version))

$npmCmd = Get-Command npm -ErrorAction SilentlyContinue
if (-not $npmCmd) {
    Write-Fail 'npm is required but not installed.'
    exit 1
}
Write-Info ("npm   : v{0}" -f (& $npmCmd.Source --version))

$codexCmd = Get-Command codex -ErrorAction SilentlyContinue
if (-not $codexCmd) {
    Write-Warn 'codex binary not found in PATH.'
    $answer = Read-Host 'Install Codex CLI globally via npm? [Y/n]'
    if ($answer -match '^[nN]') {
        Write-Fail 'codex is required to use the launcher.'
        exit 1
    }
    Write-Info 'Installing @openai/codex...'
    & $npmCmd.Source install -g '@openai/codex'
    if ($LASTEXITCODE -ne 0) {
        Write-Fail 'npm install failed. Check your npm registry / proxy config.'
        exit 1
    }
    $codexCmd = Get-Command codex -ErrorAction SilentlyContinue
    if (-not $codexCmd) {
        Write-Fail 'codex still not found after npm install - check your PATH.'
        exit 1
    }
}
$codexVer = try { (& $codexCmd.Source --version 2>$null) } catch { 'installed' }
Write-Info ("codex : {0}" -f $codexVer)

# tpl: ---------------------------------------------------------------------
# tpl: Step 3 - file ACLs on launcher + scripts
# tpl: On Windows we rely on NTFS inheritance + the user's profile ACL. We
# tpl: do NOT grant Everyone:F. We just make the launcher discoverable and
# tpl: ensure the scripts directory is readable.
# tpl: ---------------------------------------------------------------------
Write-Step '[3/6] Verifying file layout...'

$LauncherScript  = Join-Path $InstallDir 'launcher.ps1'
$UninstallScript = Join-Path $InstallDir 'uninstall.ps1'

if (-not (Test-Path -LiteralPath $LauncherScript -PathType Leaf)) {
    Write-Fail ("missing launcher.ps1 at $LauncherScript")
    exit 1
}
Write-Info ("launcher: $LauncherScript")

$ScriptsDir = Join-Path $InstallDir 'scripts'
if (Test-Path -LiteralPath $ScriptsDir -PathType Container) {
    $modCount = (Get-ChildItem -LiteralPath $ScriptsDir -Filter '*.ps1' -File).Count
    Write-Info ("shared modules: $ScriptsDir ($modCount .ps1)")
} else {
    Write-Fail "missing scripts/ at $ScriptsDir"
    exit 1
}

# tpl: ---------------------------------------------------------------------
# tpl: Step 4 - PowerShell profile block (idempotent: backup, strip old, append)
# tpl: ---------------------------------------------------------------------
Write-Step ("[4/6] Configuring PowerShell profile ($ProfilePath)...")

# tpl: function block - defines ${CORP_SLUG} as a PS function that forwards
# tpl: arguments to launcher.ps1. The here-string is double-quoted so PS
# tpl: interpolates $MarkerStart/$InstallDir/$LauncherScript at install time;
# tpl: $env: references are backtick-escaped to land in the profile as text.
$ProfileBlock = @"
$MarkerStart
# ${CORP_NAME} - installed $(Get-Date -Format 'yyyy-MM-dd')
# install_dir: $InstallDir
function ${CORP_SLUG} {
    & '$LauncherScript' @args
}
`$env:${CORP_SLUG_UPPER}_HOME = '$InstallDir'
$MarkerEnd
"@

$existing = if (Test-Path -LiteralPath $ProfilePath -PathType Leaf) {
    Get-Content -LiteralPath $ProfilePath -Raw -ErrorAction SilentlyContinue
} else { '' }

if ($existing -and $existing.Contains($MarkerStart)) {
    Write-Warn 'previous install detected - refreshing block'
    $backup = "$ProfilePath.bak"
    Copy-Item -LiteralPath $ProfilePath -Destination $backup -Force
    Write-Info ("backup: $backup")

    # tpl: strip lines from MarkerStart through MarkerEnd (inclusive). Use
    # tpl: a regex with the single-line flag so the dot matches newlines.
    $escStart = [regex]::Escape($MarkerStart)
    $escEnd   = [regex]::Escape($MarkerEnd)
    $pattern  = "(?ms)^\s*$escStart.*?$escEnd\s*\r?\n?"
    $existing = [regex]::Replace($existing, $pattern, '')
    Set-Content -LiteralPath $ProfilePath -Value $existing -NoNewline -Encoding utf8
}

Add-Content -LiteralPath $ProfilePath -Value "`n$ProfileBlock`n" -Encoding utf8
Write-Info 'block appended'

# tpl: ---------------------------------------------------------------------
# tpl: Step 5 - API token (via shared secrets-store.ps1 on Windows Credential Manager)
# tpl: ---------------------------------------------------------------------
Write-Step '[5/6] API token...'

$script:CORP_NAME       = '${CORP_NAME}'
$script:CORP_SLUG       = '${CORP_SLUG}'
$script:CORP_SLUG_UPPER = '${CORP_SLUG_UPPER}'
$script:LLM_TOKEN_URL   = '${LLM_TOKEN_URL}'

$secretsModule = Join-Path $ScriptsDir 'secrets-store.ps1'
if (-not (Test-Path -LiteralPath $secretsModule -PathType Leaf)) {
    Write-Fail "missing $secretsModule"
    exit 1
}
. $secretsModule

try { Get-ApiKey | Out-Null } catch { }

if (-not [string]::IsNullOrEmpty($script:CORP_API_KEY)) {
    Write-Info "token already stored in Windows Credential Manager; use ``${CORP_SLUG} --set-key`` to rotate"
} else {
    if (-not (Set-ApiKeyInteractive)) {
        Write-Warn "token not configured - run ``${CORP_SLUG} --set-key`` later"
    }
}

# tpl: ---------------------------------------------------------------------
# tpl: Step 6 - drop ~/.codex/config.toml (+ AGENTS.md, requirements.toml)
# tpl: Every file we generate carries GENERATED_MARKER so the uninstaller can
# tpl: distinguish managed files from user-authored ones.
# tpl: ---------------------------------------------------------------------
Write-Step '[6/6] Writing Codex config...'

$CodexHome = if ($env:CODEX_HOME) { $env:CODEX_HOME } else { Join-Path $HOME '.codex' }
if (-not (Test-Path -LiteralPath $CodexHome -PathType Container)) {
    New-Item -ItemType Directory -Path $CodexHome -Force | Out-Null
}

$ConfigDest = Join-Path $CodexHome 'config.toml'
$AgentsDest = Join-Path $CodexHome 'AGENTS.md'
$ReqsDest   = Join-Path $CodexHome 'requirements.toml'

function Copy-IfSafe {
    param(
        [Parameter(Mandatory)][string]$Source,
        [Parameter(Mandatory)][string]$Destination,
        [Parameter(Mandatory)][string]$Label
    )
    if (Test-Path -LiteralPath $Destination -PathType Leaf) {
        $content = Get-Content -LiteralPath $Destination -Raw -ErrorAction SilentlyContinue
        if ($content -and $content.Contains($GeneratedMarker)) {
            Write-Info "$Label`: refreshing managed file"
        } else {
            Write-Warn "$Label exists and was NOT generated by ${CORP_NAME}"
            $backup = "$Destination.bak"
            Write-Warn "  backing up to: $backup"
            Copy-Item -LiteralPath $Destination -Destination $backup -Force
        }
        # tpl: requirements.toml is installed read-only; clear that bit first
        try {
            $item = Get-Item -LiteralPath $Destination -ErrorAction SilentlyContinue
            if ($item -and $item.IsReadOnly) { $item.IsReadOnly = $false }
        } catch { }
    }
    Copy-Item -LiteralPath $Source -Destination $Destination -Force
}

# tpl: config.toml is mandatory
$SrcConfig = Join-Path $InstallDir 'config.toml'
if (Test-Path -LiteralPath $SrcConfig -PathType Leaf) {
    Copy-IfSafe -Source $SrcConfig -Destination $ConfigDest -Label 'config.toml'
    Write-Info ("config: $ConfigDest")
} else {
    Write-Fail "missing $SrcConfig - installer aborted"
    exit 1
}

# tpl: AGENTS.md is the white-label system identity (Codex equivalent of CLAUDE.md)
$SrcBranding = Join-Path $InstallDir 'BRANDING.md'
if (Test-Path -LiteralPath $SrcBranding -PathType Leaf) {
    Copy-IfSafe -Source $SrcBranding -Destination $AgentsDest -Label 'AGENTS.md'
    Write-Info ("agents: $AgentsDest")
}

# tpl: requirements.toml only if admin lockdown is requested
if ('${CX_REQUIRE_LOCKDOWN}' -eq 'yes') {
    $SrcReqs = Join-Path $InstallDir 'requirements.toml'
    if (Test-Path -LiteralPath $SrcReqs -PathType Leaf) {
        Copy-IfSafe -Source $SrcReqs -Destination $ReqsDest -Label 'requirements.toml'
        # tpl: lockdown file is read-only - the user must not edit it
        (Get-Item -LiteralPath $ReqsDest).IsReadOnly = $true
        Write-Info ("lockdown: $ReqsDest (read-only)")
    } else {
        Write-Warn "lockdown requested but $SrcReqs missing"
    }
} else {
    Write-Info 'lockdown: disabled by tenant config'
}

# tpl: ---------------------------------------------------------------------
# tpl: Final summary
# tpl: ---------------------------------------------------------------------
Write-Host ''
if ($script:UseColor) {
    Write-Host 'Installation complete.' -ForegroundColor Cyan
} else {
    Write-Host 'Installation complete.'
}
Write-Host ''
Write-Host '  Next steps:'
Write-Host ("    1. Reload your profile:  . '$ProfilePath'")
if ('${VPN_REQUIRED}' -eq 'yes') {
    Write-Host '    2. Connect to the corporate VPN.'
    Write-Host ("    3. Launch:               ${CORP_SLUG}")
} else {
    Write-Host ("    2. Launch:               ${CORP_SLUG}")
}
Write-Host ''
Write-Host '  Commands:'
Write-Host ("    ${CORP_SLUG}                  start interactive session")
Write-Host ("    ${CORP_SLUG} --status         show resolved env (no secret)")
Write-Host ("    ${CORP_SLUG} --set-key        rotate the API token")
Write-Host ("    ${CORP_SLUG} --help           full help")
Write-Host ''
Write-Host '  Uninstall:'
Write-Host ("    pwsh -NoProfile -File '$(Join-Path $InstallDir 'uninstall.ps1')'")
Write-Host ''
