# ${CORP_SLUG}-managed: generated by ${CORP_NAME} launcher v${CORP_LAUNCHER_VERSION}
# ${CORP_NAME} — Codex CLI admin lockdown
# Powered by ${CORP_POWERED_BY} — Authority: ${CYBER_AUTHORITY}
#
# This file is installed at $CODEX_HOME/requirements.toml with mode 0444
# (read-only). It enforces the corporate cyber baseline regardless of what
# the user sets in their own config.toml. If a setting in config.toml falls
# outside the allowlists below, Codex refuses to start.
#
# Generated only when CX_REQUIRE_LOCKDOWN = "yes" in the tenant config.
# DO NOT HAND-EDIT — rerun the launcher installer to refresh.

# tpl: ---------------------------------------------------------------------
# tpl: Provider lock — the user may only use the corporate gateway
# tpl: ---------------------------------------------------------------------
allowed_model_providers = ["${CX_PROVIDER_ID}"]
forced_model_provider = "${CX_PROVIDER_ID}"

# tpl: ---------------------------------------------------------------------
# tpl: Auth — force the gateway login method (no personal OpenAI account)
# tpl: ---------------------------------------------------------------------
forced_login_method = "${CX_FORCED_LOGIN_METHOD}"
allow_personal_api_login = false

# tpl: ---------------------------------------------------------------------
# tpl: Sandbox — only the safe modes are allowed. "danger-full-access" is
# tpl: NEVER on the allowlist regardless of tenant choice.
# tpl: ---------------------------------------------------------------------
allowed_sandbox_modes = ["read-only", "workspace-write"]
forced_sandbox_mode = "${CX_SANDBOX_MODE}"

# tpl: ---------------------------------------------------------------------
# tpl: Approval policy — the user cannot weaken below the tenant minimum.
# tpl: ---------------------------------------------------------------------
allowed_approval_policies = ["untrusted", "on-failure", "on-request"]
forced_approval_policy = "${CX_APPROVAL_POLICY}"

# tpl: ---------------------------------------------------------------------
# tpl: Network — the workspace-write sandbox must NOT have network access.
# tpl: ---------------------------------------------------------------------
[sandbox_workspace_write]
allow_network_access = false

# tpl: ---------------------------------------------------------------------
# tpl: MCP allowlist — empty by default. Add only servers approved by
# tpl: ${CYBER_AUTHORITY}. An empty list means: no local MCP servers
# tpl: may be configured by the user.
# tpl: ---------------------------------------------------------------------
allowed_mcp_servers = []

# tpl: ---------------------------------------------------------------------
# tpl: Feature flags — disable the dangerous shell tool variants. The basic
# tpl: sandboxed shell remains available; only the "danger" variants are
# tpl: blocked.
# tpl: ---------------------------------------------------------------------
[features]
shell_tool_danger = false
shell_tool_unrestricted = false
auto_update = false
external_telemetry = false
response_storage = false
history_persistence = false

# tpl: ---------------------------------------------------------------------
# tpl: Telemetry / analytics / feedback — hard off
# tpl: ---------------------------------------------------------------------
[telemetry]
allowed = false

[analytics]
allowed = false

[feedback]
allowed = false

[updates]
allowed_auto_check = false

# tpl: ---------------------------------------------------------------------
# tpl: Audit trail — point of contact for incidents
# tpl: ---------------------------------------------------------------------
[meta]
tenant = "${CORP_NAME}"
authority = "${CYBER_AUTHORITY}"
support = "${CORP_SUPPORT_CONTACT}"
launcher_version = "${CORP_LAUNCHER_VERSION}"
