#!/usr/bin/env bash
# =============================================================================
# ${CORP_NAME} — Codex CLI launcher uninstaller
# Powered by ${CORP_POWERED_BY}
#
# Idempotent. Safe to re-run. Only removes files this launcher created.
#  - shell RC block between MARKER_START / MARKER_END
#  - $CODEX_HOME/config.toml, AGENTS.md, requirements.toml IF they carry the
#    "${CORP_SLUG}-managed" header
#  - the install_dir (only when it matches the launcher home)
#  - the API key from the keychain / libsecret / fallback conf file
#
# The user's npm-installed `codex` binary is NOT removed (it may be shared
# across projects). The user's pre-existing $CODEX_HOME files (not generated
# by us) are preserved.
# =============================================================================

set -euo pipefail

INSTALL_DIR="$(cd "$(dirname "$\{BASH_SOURCE[0]\}")" && pwd)"

# tpl: ---------------------------------------------------------------------
# tpl: Colors — TTY only
# tpl: ---------------------------------------------------------------------
if [ -t 1 ]; then
    C_GREEN="\033[0;32m"
    C_RED="\033[0;31m"
    C_YELLOW="\033[0;33m"
    C_BOLD="\033[1m"
    C_DIM="\033[2m"
    C_RESET="\033[0m"
else
    C_GREEN=""; C_RED=""; C_YELLOW=""; C_BOLD=""; C_DIM=""; C_RESET=""
fi

info() { printf "  ${C_GREEN}[OK]${C_RESET} %s\n" "$1"; }
warn() { printf "  ${C_YELLOW}[!!]${C_RESET} %s\n" "$1"; }
fail() { printf "  ${C_RED}[KO]${C_RESET} %s\n" "$1" >&2; }
step() { printf "\n${C_BOLD}%s${C_RESET}\n" "$1"; }

# tpl: ---------------------------------------------------------------------
# tpl: Markers (must stay aligned with install.sh)
# tpl: ---------------------------------------------------------------------
MARKER_START="# >>> ${CORP_SLUG} >>>"
MARKER_END="# <<< ${CORP_SLUG} <<<"
GENERATED_MARKER="# ${CORP_SLUG}-managed: generated by ${CORP_NAME} launcher"

# tpl: ---------------------------------------------------------------------
# tpl: Detect OS for sed -i quirks
# tpl: ---------------------------------------------------------------------
case "$(uname -s)" in
    Darwin*) OS_TYPE="macos" ;;
    *)       OS_TYPE="other" ;;
esac

printf "\n${C_BOLD}%s — uninstaller${C_RESET}\n" "${CORP_NAME}"
printf "${C_DIM}install_dir: %s${C_RESET}\n" "$INSTALL_DIR"

# tpl: ---------------------------------------------------------------------
# tpl: Step 1 — strip RC block from every plausible shell RC file
# tpl: ---------------------------------------------------------------------
step "[1/4] Cleaning shell RC files..."

strip_rc_block() {
    local rc="$1"
    [ -f "$rc" ] || return 0
    if ! grep -qF "$MARKER_START" "$rc" 2>/dev/null; then
        return 0
    fi
    cp "$rc" "${rc}.bak"
    if [ "$OS_TYPE" = "macos" ]; then
        sed -i '' "/$\{MARKER_START\}/,/$\{MARKER_END\}/d" "$rc"
    else
        sed -i "/$\{MARKER_START\}/,/$\{MARKER_END\}/d" "$rc"
    fi
    info "removed block from $rc (backup: ${rc}.bak)"
}

for rc in "$HOME/.zshrc" "$HOME/.bashrc" "$HOME/.bash_profile" "$HOME/.profile"; do
    strip_rc_block "$rc"
done

# tpl: ---------------------------------------------------------------------
# tpl: Step 2 — remove $CODEX_HOME files generated by this launcher
# tpl: We refuse to delete a file that does NOT carry our marker — the user
# tpl: may have hand-authored it.
# tpl: ---------------------------------------------------------------------
step "[2/4] Cleaning Codex config..."

CODEX_HOME="$\{CODEX_HOME:-$HOME/.codex\}"

remove_if_managed() {
    local f="$1" label="$2"
    if [ ! -e "$f" ]; then
        return 0
    fi
    if grep -qF "$GENERATED_MARKER" "$f" 2>/dev/null; then
        # tpl: requirements.toml was chmod 0444; restore write bit first
        chmod u+w "$f" 2>/dev/null || true
        rm -f "$f"
        info "removed managed $label: $f"
    else
        warn "$label exists but was NOT generated by ${CORP_NAME} — left alone"
        warn "  path: $f"
    fi
}

remove_if_managed "$CODEX_HOME/config.toml"       "config.toml"
remove_if_managed "$CODEX_HOME/AGENTS.md"         "AGENTS.md"
remove_if_managed "$CODEX_HOME/requirements.toml" "requirements.toml"

# tpl: also clean stale .bak left by previous installs
for bak in "$CODEX_HOME"/*.bak; do
    [ -e "$bak" ] || continue
    if grep -qF "$GENERATED_MARKER" "$bak" 2>/dev/null; then
        rm -f "$bak"
        info "removed managed backup: $bak"
    fi
done

# tpl: ---------------------------------------------------------------------
# tpl: Step 3 — remove the API token from secret store + fallback conf
# tpl: ---------------------------------------------------------------------
step "[3/4] Removing API token..."

if command -v security >/dev/null 2>&1; then
    if security delete-generic-password -s "${CORP_SLUG}" -a "$USER" >/dev/null 2>&1; then
        info "macOS keychain: removed entry for ${CORP_SLUG}"
    fi
fi

if command -v secret-tool >/dev/null 2>&1; then
    secret-tool clear service "${CORP_SLUG}" username "$USER" >/dev/null 2>&1 || true
    info "libsecret: cleared entry for ${CORP_SLUG}"
fi

CONF_FILE="$HOME/.${CORP_SLUG}.conf"
if [ -f "$CONF_FILE" ]; then
    rm -f "$CONF_FILE"
    info "removed $CONF_FILE"
fi

# tpl: ---------------------------------------------------------------------
# tpl: Step 4 — remove the install dir itself (only if we are inside it AND
# tpl: it looks like a launcher tree — refuse otherwise)
# tpl: ---------------------------------------------------------------------
step "[4/4] Removing install directory..."

is_launcher_dir() {
    [ -f "$INSTALL_DIR/${CORP_SLUG}" ] \
        && [ -f "$INSTALL_DIR/uninstall.sh" ] \
        && [ -d "$INSTALL_DIR/scripts" ]
}

if ! is_launcher_dir; then
    warn "install_dir does not look like a ${CORP_NAME} launcher tree — left alone"
    warn "  path: $INSTALL_DIR"
elif [ "$INSTALL_DIR" = "$HOME" ] || [ "$INSTALL_DIR" = "/" ]; then
    fail "refusing to delete $INSTALL_DIR (looks like a home or root path)"
    exit 1
else
    # tpl: launch removal from /tmp so we don't pull the rug from under our feet
    TMP_SCRIPT="$(mktemp -t ${CORP_SLUG}-uninstall-XXXXXX.sh)"
    cat > "$TMP_SCRIPT" <<EOF_TMP
#!/usr/bin/env bash
set -euo pipefail
sleep 0.2
rm -rf "$INSTALL_DIR"
rm -f "\$0"
EOF_TMP
    chmod 700 "$TMP_SCRIPT"
    info "scheduling removal of $INSTALL_DIR"
    nohup "$TMP_SCRIPT" >/dev/null 2>&1 &
fi

printf "\n${C_BOLD}Uninstall complete.${C_RESET}\n"
printf "${C_DIM}Reload your shell (source your RC) to drop the function/alias.${C_RESET}\n\n"
