{
  "//": "${CORP_SLUG}-managed: generated by ${CORP_NAME} launcher v${CORP_LAUNCHER_VERSION}",
  "//1": "Managed by ${CORP_NAME} — Powered by ${CORP_POWERED_BY}",
  "//2": "This block is merged into the user's settings.json by the launcher.",
  "//3": "Hand-edits to cline.* keys will be overwritten on the next refresh.",
  "//4": "Cline marketplace id: saoudrizwan.claude-dev",

  "cline.apiProvider": "openai",
  "cline.openAiBaseUrl": "${LLM_OPENAI_BASE_URL}",
  "cline.openAiApiKey": "${CORP_API_KEY}",
  "cline.openAiModelId": "${LLM_PRIMARY_MODEL}",
  "cline.openAiModelInfo": {
    "supportsImages": false,
    "supportsComputerUse": false,
    "supportsPromptCache": false,
    "contextWindow": 200000,
    "maxTokens": 8192
  },

  "cline.customInstructions": "${INSTALL_DIR}/BRANDING.md",

  "cline.telemetryOptOut": true,
  "cline.errorReportingOptOut": true,
  "cline.allowAutoUpdate": false,

  "cline.autoApprove": {
    "enabled": false,
    "actions": {
      "readFiles": false,
      "editFiles": false,
      "executeSafeCommands": false,
      "executeAllCommands": false,
      "useBrowser": false,
      "useMcp": false
    },
    "maxRequests": 20,
    "enableNotifications": true
  },

  "cline.mcpMarketplaceEnabled": false,
  "cline.enableCheckpoints": true,

  "//security": "Do NOT disable VS Code workspace folder trust — Cline runs commands in trusted workspaces only.",
  "security.workspace.trust.enabled": true,
  "security.workspace.trust.untrustedFiles": "prompt",

  "//proxy": "VS Code proxy & TLS — applies to every extension running in the host, including Cline.",
  "http.proxy": "${CORP_HTTPS_PROXY}",
  "http.proxyStrictSSL": true,
  "http.proxySupport": "on",
  "http.systemCertificates": true,

  "//telemetry": "VS Code-level telemetry kill switch (extension host inherits this).",
  "telemetry.telemetryLevel": "off",
  "redhat.telemetry.enabled": false
}
