# ${CORP_SLUG}-managed: generated by ${CORP_NAME} launcher v${CORP_LAUNCHER_VERSION}
# Managed by ${CORP_NAME} — do not edit
# Powered by ${CORP_POWERED_BY}
#
# This file is rewritten by the launcher installer. To change any value,
# edit the launcher templates and re-run the installer — hand-edits will
# be overwritten on the next install/update.
#
# tpl: aider reads this from ~/.aider.conf.yml by default (overridable via
# tpl: $AIDER_CONFIG). All settings here are also mirrored as env vars in
# tpl: the launcher; the config file is the persistent line of defense in
# tpl: case the env is stripped by a child process.

# tpl: ---------------------------------------------------------------------
# tpl: Gateway endpoint (LiteLLM-compatible) + model selection
# tpl: ---------------------------------------------------------------------
openai-api-base: ${LLM_OPENAI_BASE_URL}
model: ${LLM_PRIMARY_MODEL}
weak-model: $\{LLM_WEAK_MODEL:-${LLM_PRIMARY_MODEL}\}

# tpl: ---------------------------------------------------------------------
# tpl: Safety defaults — never auto-commit, never auto-update
# tpl: The user must explicitly review and commit changes themselves.
# tpl: ---------------------------------------------------------------------
auto-commits: false
dirty-commits: false
attribute-author: false
attribute-committer: false

# tpl: ---------------------------------------------------------------------
# tpl: Telemetry / analytics / update checks — all off
# tpl: ---------------------------------------------------------------------
analytics-disable: true
check-update: false
show-release-notes: false

# tpl: ---------------------------------------------------------------------
# tpl: TLS verification
# tpl: When the tenant accepted TLS inspection (ACCEPT_TLS_INSPECTION=yes)
# tpl: we must set verify-ssl: false so httpx accepts the inspecting cert.
# tpl: When a corporate CA bundle is provided, verify-ssl stays true and
# tpl: REQUESTS_CA_BUNDLE / SSL_CERT_FILE point at it.
# tpl: ---------------------------------------------------------------------
verify-ssl: $\{ACCEPT_TLS_INSPECTION_INVERTED:-true\}

# tpl: ---------------------------------------------------------------------
# tpl: Editor / UI defaults
# tpl: ---------------------------------------------------------------------
dark-mode: true
pretty: true
stream: true
gitignore: true

# tpl: ---------------------------------------------------------------------
# tpl: History files — keep local, never upload
# tpl: ---------------------------------------------------------------------
input-history-file: $\{HOME\}/.aider.input.history
chat-history-file: $\{HOME\}/.aider.chat.history.md
llm-history-file: $\{HOME\}/.aider.llm.history

# tpl: ---------------------------------------------------------------------
# tpl: Token / cost guards — keep the user in control
# tpl: ---------------------------------------------------------------------
map-tokens: 1024
max-chat-history-tokens: 8192
