#!/usr/bin/env bash
# =====================================================================
#  ${CORP_NAME} — Aider launcher installer
#  Powered by ${CORP_POWERED_BY}
#
#  Idempotent. Re-runnable. Backs up the shell RC before modifying it.
#  - Verifies Python 3.10+ and pipx
#  - Installs aider via `pipx install aider-install && aider-install`
#  - Writes a managed ~/.aider.conf.yml (marker-tagged)
#  - Wires an idempotent ${CORP_SLUG} function block into the shell RC
# =====================================================================

set -euo pipefail
umask 077

INSTALL_DIR="$(cd "$(dirname "$\{BASH_SOURCE[0]\}")" && pwd)"
LAUNCHER_VERSION="${CORP_LAUNCHER_VERSION}"

# tpl: ---------------------------------------------------------------------
# tpl: Colors — TTY only
# tpl: ---------------------------------------------------------------------
if [ -t 1 ]; then
    ORANGE="\033[38;5;${BANNER_COLOR_PRIMARY}m"
    GREEN="\033[32m"
    RED="\033[31m"
    YELLOW="\033[33m"
    BOLD="\033[1m"
    DIM="\033[2m"
    RESET="\033[0m"
else
    ORANGE=""; GREEN=""; RED=""; YELLOW=""; BOLD=""; DIM=""; RESET=""
fi

info()  { printf '  $\{GREEN\}[OK]$\{RESET\} %s\n' "$*"; }
warn()  { printf '  $\{YELLOW\}[!]$\{RESET\}  %s\n' "$*"; }
fail()  { printf '  $\{RED\}[KO]$\{RESET\} %s\n' "$*" >&2; }
step()  { printf '\n$\{BOLD\}%s$\{RESET\}\n' "$*"; }
ask()   { printf '  $\{YELLOW\}%s [y/N] $\{RESET\}' "$*"; read -r ans; case "$ans" in [yY]*) return 0 ;; *) return 1 ;; esac; }

# tpl: ---------- detection ----------
detect_os() {
    case "$(uname -s)" in
        Darwin*) OS_TYPE="macos"; OS_LABEL="macOS $(sw_vers -productVersion 2>/dev/null || echo '')" ;;
        Linux*)
            if grep -qi microsoft /proc/version 2>/dev/null; then
                OS_TYPE="wsl"; OS_LABEL="Windows (WSL)"
            else
                OS_TYPE="linux"; OS_LABEL="Linux"
            fi
            ;;
        MINGW*|MSYS*|CYGWIN*) OS_TYPE="gitbash"; OS_LABEL="Git Bash (Windows)" ;;
        *) OS_TYPE="unknown"; OS_LABEL="Unknown" ;;
    esac
}

detect_shell_rc() {
    local shell_name
    shell_name=$(basename "$\{SHELL:-/bin/sh\}")
    case "$shell_name" in
        zsh)  SHELL_NAME="zsh";  SHELL_RC="$HOME/.zshrc" ;;
        bash) SHELL_NAME="bash"
              if [ "$OS_TYPE" = "macos" ] && [ -f "$HOME/.bash_profile" ]; then
                  SHELL_RC="$HOME/.bash_profile"
              else
                  SHELL_RC="$HOME/.bashrc"
              fi
              ;;
        fish) SHELL_NAME="fish"; SHELL_RC="$HOME/.config/fish/conf.d/${CORP_SLUG}.fish" ;;
        *)    SHELL_NAME="sh";   SHELL_RC="$HOME/.profile" ;;
    esac
    [ -f "$SHELL_RC" ] || { mkdir -p "$(dirname "$SHELL_RC")" && touch "$SHELL_RC"; }
}

show_banner() {
    printf '\n$\{ORANGE\}$\{BOLD\}'
    printf '  ╔═══════════════════════════════════════════════╗\n'
    printf '  ║  %-44s ║\n' "${CORP_NAME} — installer"
    printf '  ║  %-44s ║\n' "Powered by ${CORP_POWERED_BY}"
    printf '  ╚═══════════════════════════════════════════════╝\n'
    printf '$\{RESET\}\n'
}

# tpl: ---------- markers (must stay in sync with uninstall.sh) ----------
MARKER_START="# >>> ${CORP_SLUG} >>>"
MARKER_END="# <<< ${CORP_SLUG} <<<"
GENERATED_MARKER="# ${CORP_SLUG}-managed: generated by ${CORP_NAME} launcher v${CORP_LAUNCHER_VERSION}"

# tpl: ---------- begin ----------
show_banner

step "[1/7] Detect environment"
detect_os
if [ "$OS_TYPE" = "unknown" ]; then
    fail "Unsupported OS. Supported: macOS, Linux, WSL, Git Bash."
    exit 1
fi
info "OS         : $OS_LABEL"
detect_shell_rc
info "Shell RC   : $SHELL_RC"
info "Install dir: $INSTALL_DIR"

# tpl: ---------------------------------------------------------------------
# tpl: Step 2 — Python 3.10+ and pipx
# tpl: aider-install drops a self-contained venv so we don't pollute the
# tpl: system Python. Requires Python 3.10+ on the host.
# tpl: ---------------------------------------------------------------------
step "[2/7] Check Python 3.10+"
PYTHON_BIN=""
for candidate in python3.13 python3.12 python3.11 python3.10 python3 python; do
    if command -v "$candidate" >/dev/null 2>&1; then
        ver=$("$candidate" -c 'import sys; print("%d.%d" % sys.version_info[:2])' 2>/dev/null || echo "0.0")
        major=$\{ver%%.*\}
        minor=$\{ver##*.\}
        if [ "$major" -ge 3 ] && [ "$minor" -ge 10 ]; then
            PYTHON_BIN="$candidate"
            info "python: $candidate ($ver)"
            break
        fi
    fi
done
if [ -z "$PYTHON_BIN" ]; then
    fail "Python 3.10+ is required. Install via your corporate package manager."
    [ "$OS_TYPE" = "macos" ]  && fail "  macOS: brew install python@3.12"
    [ "$OS_TYPE" = "linux" ]  && fail "  Debian/Ubuntu: apt install python3 python3-venv"
    exit 1
fi

step "[3/7] Check pipx"
if ! command -v pipx >/dev/null 2>&1; then
    warn "pipx not found."
    if [ "$OS_TYPE" = "macos" ] && command -v brew >/dev/null 2>&1; then
        if ask "Install pipx via Homebrew?"; then
            brew install pipx || { fail "brew install pipx failed"; exit 1; }
            pipx ensurepath || true
        else
            fail "pipx is required to install aider."
            exit 1
        fi
    else
        if ask "Install pipx via 'python3 -m pip install --user pipx'?"; then
            "$PYTHON_BIN" -m pip install --user pipx || { fail "pip install pipx failed"; exit 1; }
            "$PYTHON_BIN" -m pipx ensurepath || true
            # tpl: make pipx visible in this shell for the next step
            export PATH="$HOME/.local/bin:$PATH"
        else
            fail "pipx is required to install aider."
            exit 1
        fi
    fi
fi
info "pipx: $(pipx --version 2>/dev/null || echo installed)"

# tpl: ---------------------------------------------------------------------
# tpl: Step 4 — aider (via aider-install for an isolated venv)
# tpl: ---------------------------------------------------------------------
step "[4/7] Install aider"
if command -v aider >/dev/null 2>&1; then
    info "aider already installed: $(aider --version 2>/dev/null || echo unknown)"
    if ask "Upgrade aider to the latest version?"; then
        pipx upgrade aider-install 2>/dev/null || pipx install --force aider-install
        aider-install || true
    fi
else
    info "Installing aider-install via pipx..."
    pipx install aider-install || { fail "pipx install aider-install failed"; exit 1; }
    info "Running aider-install bootstrap..."
    aider-install || { fail "aider-install failed"; exit 1; }
fi

if ! command -v aider >/dev/null 2>&1; then
    warn "aider not in PATH yet — open a new shell or 'source $SHELL_RC' after install."
fi

# tpl: ---------------------------------------------------------------------
# tpl: Step 5 — permissions
# tpl: ---------------------------------------------------------------------
step "[5/7] Set permissions"
chmod 755 "$INSTALL_DIR/${CORP_SLUG}"
info "launcher executable: $INSTALL_DIR/${CORP_SLUG}"
if [ -d "$INSTALL_DIR/scripts" ]; then
    find "$INSTALL_DIR/scripts" -type f -name "*.sh" -exec chmod 644 {} \;
    info "shared modules: $INSTALL_DIR/scripts/"
fi
chmod 755 "$INSTALL_DIR/uninstall.sh" 2>/dev/null || true

# tpl: ---------------------------------------------------------------------
# tpl: Step 6 — shell RC block (idempotent)
# tpl: ---------------------------------------------------------------------
step "[6/7] Wire up the shell ($SHELL_RC)"

if grep -qF "$MARKER_START" "$SHELL_RC" 2>/dev/null; then
    cp "$SHELL_RC" "$\{SHELL_RC\}.${CORP_SLUG}.bak"
    info "Backup saved at $\{SHELL_RC\}.${CORP_SLUG}.bak"
    if [ "$OS_TYPE" = "macos" ]; then
        sed -i '' "/$MARKER_START/,/$MARKER_END/d" "$SHELL_RC"
    else
        sed -i "/$MARKER_START/,/$MARKER_END/d" "$SHELL_RC"
    fi
    info "Removed previous block"
fi

{
    printf '\n%s\n' "$MARKER_START"
    printf '# %s — Powered by %s\n' "${CORP_NAME}" "${CORP_POWERED_BY}"
    printf '# Installed on %s\n' "$(date +%Y-%m-%d)"
    printf 'export ${CORP_SLUG_UPPER}_HOME="%s"\n' "$INSTALL_DIR"
    printf '${CORP_SLUG}() { "$\{${CORP_SLUG_UPPER}_HOME\}/${CORP_SLUG}" "$@"; }\n'
    printf '%s\n' "$MARKER_END"
} >> "$SHELL_RC"
info "Shell block added"

# tpl: ---------------------------------------------------------------------
# tpl: Step 7 — managed ~/.aider.conf.yml + API token
# tpl: ---------------------------------------------------------------------
step "[7/7] Configure aider + API token"

AIDER_CONF_DEST="$HOME/.aider.conf.yml"
if [ -r "$INSTALL_DIR/aider.conf.yml" ]; then
    if [ -f "$AIDER_CONF_DEST" ]; then
        if grep -qF "$GENERATED_MARKER" "$AIDER_CONF_DEST" 2>/dev/null; then
            info "Refreshing managed ~/.aider.conf.yml"
        else
            warn "Existing ~/.aider.conf.yml was NOT generated by ${CORP_NAME}"
            cp "$AIDER_CONF_DEST" "$\{AIDER_CONF_DEST\}.${CORP_SLUG}.bak"
            warn "  backup: $\{AIDER_CONF_DEST\}.${CORP_SLUG}.bak"
        fi
    fi
    install -m 0644 "$INSTALL_DIR/aider.conf.yml" "$AIDER_CONF_DEST"
    info "Wrote $AIDER_CONF_DEST"
else
    fail "missing $INSTALL_DIR/aider.conf.yml — installer aborted"
    exit 1
fi

export CORP_NAME="${CORP_NAME}"
export CORP_SLUG="${CORP_SLUG}"
export CORP_SLUG_UPPER="${CORP_SLUG_UPPER}"
export LLM_TOKEN_URL="${LLM_TOKEN_URL}"

# shellcheck disable=SC1091
. "$INSTALL_DIR/scripts/secrets-store.sh"

load_api_key || true
if [ -n "$\{CORP_API_KEY:-\}" ]; then
    if ask "An API token is already stored. Replace it?"; then
        prompt_for_api_key
    fi
else
    prompt_for_api_key || warn "token not configured — run '${CORP_SLUG} --set-key' later"
fi

# tpl: ---------------------------------------------------------------------
# tpl: Done
# tpl: ---------------------------------------------------------------------
printf '\n$\{ORANGE\}$\{BOLD\}  Installation complete.$\{RESET\}\n\n'
printf '  Reload your shell : $\{GREEN\}source %s$\{RESET\}\n' "$SHELL_RC"
printf '  Launch with       : $\{GREEN\}${CORP_SLUG}$\{RESET\}\n'
printf '  Diagnostics       : $\{DIM\}${CORP_SLUG} --status$\{RESET\}\n'
printf '  Uninstall         : $\{DIM\}${CORP_SLUG} --uninstall$\{RESET\}\n\n'
[ "${VPN_REQUIRED}" = "yes" ] && printf '  $\{YELLOW\}[!]$\{RESET\}  Corporate VPN required before first launch.\n\n'
