#!/usr/bin/env bash
# =====================================================================
#  ${CORP_NAME} — Aider launcher uninstaller
#  Powered by ${CORP_POWERED_BY}
#
#  Idempotent: safe to run multiple times.
#  - Removes the shell RC block (with backup)
#  - Deletes ~/.aider.conf.yml only if it carries our marker
#  - Removes the API token from keychain / libsecret / fallback file
#  - Optionally uninstalls aider (pipx) and removes the install dir
# =====================================================================

set -euo pipefail

INSTALL_DIR="$(cd "$(dirname "$\{BASH_SOURCE[0]\}")" && pwd)"

if [ -t 1 ]; then
    RED="\033[31m"
    GREEN="\033[32m"
    YELLOW="\033[33m"
    DIM="\033[2m"
    BOLD="\033[1m"
    RESET="\033[0m"
else
    RED=""; GREEN=""; YELLOW=""; DIM=""; BOLD=""; RESET=""
fi

info() { printf '  $\{GREEN\}[OK]$\{RESET\} %s\n' "$*"; }
warn() { printf '  $\{YELLOW\}[!]$\{RESET\}  %s\n' "$*"; }
skip() { printf '  $\{DIM\}[--]$\{RESET\} %s\n' "$*"; }
fail() { printf '  $\{RED\}[KO]$\{RESET\} %s\n' "$*" >&2; }

printf '$\{BOLD\}${CORP_NAME} — uninstalling$\{RESET\}\n\n'

OS_TYPE="linux"
case "$(uname -s)" in
    Darwin*) OS_TYPE="macos" ;;
    MINGW*|MSYS*|CYGWIN*) OS_TYPE="gitbash" ;;
esac

# tpl: ---------- 1. detect shell RC ----------
detect_shell_rc() {
    local shell_name
    shell_name=$(basename "$\{SHELL:-/bin/sh\}")
    case "$shell_name" in
        zsh)  SHELL_RC="$HOME/.zshrc" ;;
        bash)
            if [ "$OS_TYPE" = "macos" ] && [ -f "$HOME/.bash_profile" ]; then
                SHELL_RC="$HOME/.bash_profile"
            else
                SHELL_RC="$HOME/.bashrc"
            fi
            ;;
        fish) SHELL_RC="$HOME/.config/fish/conf.d/${CORP_SLUG}.fish" ;;
        *)    SHELL_RC="$HOME/.profile" ;;
    esac
}
detect_shell_rc

# tpl: ---------- 2. remove shell RC block ----------
MARKER_START="# >>> ${CORP_SLUG} >>>"
MARKER_END="# <<< ${CORP_SLUG} <<<"
GENERATED_MARKER="# ${CORP_SLUG}-managed: generated by ${CORP_NAME} launcher v${CORP_LAUNCHER_VERSION}"

if [ -f "$SHELL_RC" ] && grep -qF "$MARKER_START" "$SHELL_RC" 2>/dev/null; then
    cp "$SHELL_RC" "$\{SHELL_RC\}.${CORP_SLUG}.uninstall.bak"
    if [ "$OS_TYPE" = "macos" ]; then
        sed -i '' "/$MARKER_START/,/$MARKER_END/d" "$SHELL_RC"
    else
        sed -i "/$MARKER_START/,/$MARKER_END/d" "$SHELL_RC"
    fi
    info "Removed shell RC block from $SHELL_RC (backup: $\{SHELL_RC\}.${CORP_SLUG}.uninstall.bak)"
else
    skip "No shell block found in $SHELL_RC"
fi

# tpl: ---------- 3. remove ~/.aider.conf.yml if it was ours ----------
AIDER_CONF="$HOME/.aider.conf.yml"
if [ -f "$AIDER_CONF" ]; then
    if grep -qF "$GENERATED_MARKER" "$AIDER_CONF" 2>/dev/null \
       || grep -qF "Managed by ${CORP_NAME}" "$AIDER_CONF" 2>/dev/null; then
        # tpl: leave a backup in case the user wants to inspect it
        cp "$AIDER_CONF" "$\{AIDER_CONF\}.${CORP_SLUG}.uninstall.bak"
        rm -f "$AIDER_CONF"
        info "Removed managed $AIDER_CONF (backup: $\{AIDER_CONF\}.${CORP_SLUG}.uninstall.bak)"
    else
        skip "$AIDER_CONF is not corporate-managed — left in place"
    fi
fi

# tpl: ---------- 4. clear API token from secret stores ----------
if command -v security >/dev/null 2>&1; then
    if security delete-generic-password -s "${CORP_SLUG}" -a "$USER" >/dev/null 2>&1; then
        info "Removed keychain entry"
    else
        skip "No keychain entry to remove"
    fi
fi
if command -v secret-tool >/dev/null 2>&1; then
    if secret-tool clear service "${CORP_SLUG}" username "$USER" 2>/dev/null; then
        info "Removed libsecret entry"
    else
        skip "No libsecret entry to remove"
    fi
fi
if [ -f "$HOME/.${CORP_SLUG}.conf" ]; then
    rm -f "$HOME/.${CORP_SLUG}.conf"
    info "Removed $HOME/.${CORP_SLUG}.conf"
fi

# tpl: ---------- 5. optionally uninstall aider via pipx ----------
if command -v pipx >/dev/null 2>&1; then
    if pipx list 2>/dev/null | grep -q '^package aider-install '; then
        printf '  $\{YELLOW\}Uninstall aider (pipx)? [y/N]$\{RESET\} '
        read -r ans
        case "$ans" in
            [yY]*)
                pipx uninstall aider-install >/dev/null 2>&1 && info "Removed aider-install via pipx" || warn "pipx uninstall failed"
                pipx uninstall aider-chat   >/dev/null 2>&1 && info "Removed aider-chat via pipx"   || true
                ;;
            *)  skip "Kept aider installation (remove manually with 'pipx uninstall aider-chat')" ;;
        esac
    fi
fi

# tpl: ---------- 6. remove install dir (with defensive guards) ----------
if [ -z "$INSTALL_DIR" ] || [ "$INSTALL_DIR" = "/" ] || [ "$INSTALL_DIR" = "$HOME" ]; then
    warn "Refusing to delete suspicious INSTALL_DIR: '$INSTALL_DIR'"
elif [ -d "$INSTALL_DIR" ]; then
    printf '  $\{YELLOW\}Remove install directory %s? [y/N]$\{RESET\} ' "$INSTALL_DIR"
    read -r ans
    case "$ans" in
        [yY]*)
            PARENT_DIR="$(dirname "$INSTALL_DIR")"
            cd "$PARENT_DIR"
            rm -rf "$INSTALL_DIR"
            info "Removed $INSTALL_DIR"
            ;;
        *)
            skip "Kept $INSTALL_DIR — remove manually if desired"
            ;;
    esac
fi

printf '\n$\{GREEN\}$\{BOLD\}Uninstall complete.$\{RESET\}\n'
printf '  Reload your shell to drop the ${CORP_SLUG} command:\n'
printf '    $\{DIM\}source %s$\{RESET\}\n\n' "$SHELL_RC"
