#!/usr/bin/env bash
# tpl: ${CORP_NAME} — Vertex AI / Gemini CLI usage adapter
# tpl: Powered by ${CORP_POWERED_BY}
# tpl: Generated by the corporate-launcher skill — do not edit by hand.
#
# tpl: WHY THIS EXISTS
# tpl:   The shared strip-proxy.js intercepts Anthropic-style SSE only. Vertex AI
# tpl:   speaks a different protocol (StreamGenerateContent / Cloud AI Platform
# tpl:   gRPC-JSON) that the proxy does not parse. Without this adapter, the
# tpl:   /tmp/${CORP_SLUG}-usage.jsonl ledger stays empty for Gemini users and
# tpl:   `<launcher> --cost` returns nothing.
# tpl:
# tpl: STRATEGY
# tpl:   Gemini CLI exposes native OpenTelemetry with a file sink:
# tpl:     ~/.gemini/settings.json -> telemetry.outfile
# tpl:   When enabled, each completed request emits a `gemini_cli.api_response`
# tpl:   log record carrying:
# tpl:     - model              (string)
# tpl:     - input_token_count  (int)
# tpl:     - output_token_count (int)
# tpl:     - session.id         (common attribute)
# tpl:     - prompt_id          (string)
# tpl:   We tail that file, project each api_response into the canonical
# tpl:   cost-tracker schema, and append to the shared JSONL ledger.
# tpl:
# tpl:   This is a REAL measurement (not an estimate) — the token counts come
# tpl:   from Vertex's own usageMetadata, surfaced verbatim by gemini-cli.
# tpl:
# tpl: PRIVACY GUARDRAIL
# tpl:   target=local + outfile means OTLP data NEVER leaves the host. No
# tpl:   otlpEndpoint, no GCP export. The adapter also enforces this by
# tpl:   rewriting the telemetry block on each start.
# tpl:
# tpl: LIFECYCLE
# tpl:   Spawned in background by launcher.sh before `exec gemini`. The launcher
# tpl:   captures the PID in ${CORP_SLUG_UPPER}_USAGE_ADAPTER_PID and traps EXIT
# tpl:   to kill it. No daemon, no systemd, no leftover process.

set -euo pipefail

# --- Resolved at install time -------------------------------------------------
CORP_NAME="${CORP_NAME}"
CORP_SLUG="${CORP_SLUG}"
CORP_SLUG_UPPER="${CORP_SLUG_UPPER}"
COST_CURRENCY="${COST_CURRENCY}"

# --- Runtime config -----------------------------------------------------------
USAGE_LOG="$\{${CORP_SLUG_UPPER}_USAGE_LOG:-/tmp/$\{CORP_SLUG\}-usage.jsonl\}"
TELEMETRY_FILE="$\{GEMINI_TELEMETRY_OUTFILE:-$HOME/.gemini/telemetry.log\}"
SESSION="$\{${CORP_SLUG_UPPER}_SESSION_ID:-\}"
VERBOSE="$\{${CORP_SLUG_UPPER}_USAGE_ADAPTER_VERBOSE:-0\}"

# tpl: Pricing table — keep in sync with scripts/pricing.json
# tpl: Per 1M tokens, in COST_CURRENCY. Vertex bills input + output only;
# tpl: cached tokens and thinking tokens are billed at input rate for now.
# tpl: Edit to match your contracted Vertex AI rates.
declare -A PRICE_INPUT
declare -A PRICE_OUTPUT
PRICE_INPUT["${GM_PRIMARY_MODEL}"]=1.25
PRICE_OUTPUT["${GM_PRIMARY_MODEL}"]=10.0
# tpl: Sensible defaults for known Gemini families; fuzzy-matched below.
PRICE_INPUT["gemini-2.5-pro"]=1.25;       PRICE_OUTPUT["gemini-2.5-pro"]=10.0
PRICE_INPUT["gemini-2.5-flash"]=0.30;     PRICE_OUTPUT["gemini-2.5-flash"]=2.5
PRICE_INPUT["gemini-2.5-flash-lite"]=0.10; PRICE_OUTPUT["gemini-2.5-flash-lite"]=0.40
PRICE_INPUT["gemini-3-pro"]=2.50;         PRICE_OUTPUT["gemini-3-pro"]=15.0

vlog() {
    [ "$VERBOSE" = "1" ] && printf '[%s-usage] %s\n' "$CORP_SLUG" "$*" >&2 || true
}

# -----------------------------------------------------------------------------
# Step 1: ensure Gemini CLI telemetry is locally enabled, file sink only.
# -----------------------------------------------------------------------------
ensure_telemetry_config() {
    local cfg_dir="$HOME/.gemini"
    local cfg_file="$cfg_dir/settings.json"
    mkdir -p "$cfg_dir"
    if [ ! -f "$cfg_file" ]; then
        printf '{}\n' > "$cfg_file"
    fi
    # tpl: Use python (always present — cost-tracker is python) for safe JSON edit.
    python3 - "$cfg_file" "$TELEMETRY_FILE" <<'PY' || vlog "could not patch settings.json"
import json, sys, pathlib
p = pathlib.Path(sys.argv[1]); outfile = sys.argv[2]
try:
    cfg = json.loads(p.read_text(encoding="utf-8") or "{}")
except json.JSONDecodeError:
    cfg = {}
tel = cfg.setdefault("telemetry", {})
tel["enabled"] = True
tel["target"] = "local"
tel["outfile"] = outfile
tel.pop("otlpEndpoint", None)  # privacy: never export off-host
p.write_text(json.dumps(cfg, indent=2) + "\n", encoding="utf-8")
PY
    # tpl: Make sure the file exists so `tail -F` doesn't fail on a brand-new install.
    : > "$TELEMETRY_FILE" 2>/dev/null || touch "$TELEMETRY_FILE"
}

# -----------------------------------------------------------------------------
# Step 2: tail + parse loop.
# -----------------------------------------------------------------------------
# tpl: tail -F follows truncations and rotations. Each line is one OTel record.
# tpl: Records of interest contain "gemini_cli.api_response" as event name OR
# tpl: have body.event_name == that value. We accept either shape.
run_tail() {
    ensure_telemetry_config
    vlog "tailing $TELEMETRY_FILE, writing $USAGE_LOG, session=$SESSION"

    # shellcheck disable=SC2094
    tail -n0 -F "$TELEMETRY_FILE" 2>/dev/null | \
        ${CORP_SLUG_UPPER}_USAGE_LOG="$USAGE_LOG" \
        ${CORP_SLUG_UPPER}_SESSION_ID="$SESSION" \
        ${CORP_SLUG_UPPER}_VERBOSE="$VERBOSE" \
        COST_CURRENCY="$COST_CURRENCY" \
        python3 - <<'PY'
import json, os, sys, time, datetime as dt, re

USAGE_LOG = os.environ["${CORP_SLUG_UPPER}_USAGE_LOG"]
SESSION   = os.environ.get("${CORP_SLUG_UPPER}_SESSION_ID") or None
VERBOSE   = os.environ.get("${CORP_SLUG_UPPER}_VERBOSE") == "1"

# tpl: Pricing — duplicated from the bash table because the python subshell
# tpl: cannot see bash assoc arrays. Keep in sync with the block above and
# tpl: with scripts/pricing.json. (Templating: render-time substitution is
# tpl: handled by scripts/render.py, same as cost-tracker.py.tpl.)
PRICING = {
    "${GM_PRIMARY_MODEL}":     {"input": 1.25, "output": 10.0},
    "gemini-2.5-pro":          {"input": 1.25, "output": 10.0},
    "gemini-2.5-flash":        {"input": 0.30, "output": 2.5},
    "gemini-2.5-flash-lite":   {"input": 0.10, "output": 0.40},
    "gemini-3-pro":            {"input": 2.50, "output": 15.0},
}

def vlog(*a):
    if VERBOSE:
        print("[${CORP_SLUG}-usage]", *a, file=sys.stderr, flush=True)

def price_for(model):
    if not model:
        return None
    if model in PRICING:
        return PRICING[model]
    # tpl: fuzzy — Vertex may return "publishers/google/models/gemini-2.5-pro"
    for k, v in PRICING.items():
        if k in model or model in k:
            return v
    return None

def cost_of(usage, model):
    p = price_for(model)
    if not p:
        return None
    i = usage.get("input_tokens", 0) or 0
    o = usage.get("output_tokens", 0) or 0
    return (i / 1e6) * p["input"] + (o / 1e6) * p["output"]

# tpl: api_response shape (observed via gemini-cli local OTLP sink):
#   { "body": {...}, "attributes": {...}, "name": "gemini_cli.api_response", ... }
# tpl: Some sink formats put the event under "body.event.name" instead — we
# tpl: handle both. Token counts may live in body.* OR attributes.*.
def extract(record):
    name = record.get("name") or record.get("event_name") \
           or (record.get("body") or {}).get("event_name") \
           or (record.get("attributes") or {}).get("event.name")
    if name != "gemini_cli.api_response":
        return None
    body  = record.get("body") if isinstance(record.get("body"), dict) else {}
    attrs = record.get("attributes") if isinstance(record.get("attributes"), dict) else {}
    merged = {**body, **attrs}
    model = merged.get("model") or merged.get("gen_ai.request.model")
    inp   = merged.get("input_token_count")  or merged.get("gen_ai.usage.input_tokens")
    out   = merged.get("output_token_count") or merged.get("gen_ai.usage.output_tokens")
    sid   = merged.get("session.id") or merged.get("session_id") or SESSION
    if inp is None and out is None:
        return None
    return {
        "ts":      dt.datetime.utcnow().isoformat(timespec="seconds") + "Z",
        "session": sid,
        "model":   model or "unknown",
        "usage":   {"input_tokens": int(inp or 0), "output_tokens": int(out or 0)},
        "cost":    cost_of({"input_tokens": int(inp or 0), "output_tokens": int(out or 0)},
                           model or ""),
    }

# tpl: stream-process; never load file fully. Each line = one JSON record.
for line in sys.stdin:
    line = line.strip()
    if not line or not line.startswith("{"):
        continue
    try:
        rec = json.loads(line)
    except json.JSONDecodeError:
        vlog("non-JSON line, skipped")
        continue
    entry = extract(rec)
    if not entry:
        continue
    try:
        with open(USAGE_LOG, "a", encoding="utf-8") as fh:
            fh.write(json.dumps(entry) + "\n")
        vlog("logged", entry["model"], entry["usage"], "cost=", entry.get("cost"))
    except OSError as e:
        vlog("write failed:", e)
PY
}

# tpl: When invoked directly: run the tail loop. When sourced (rare), expose
# tpl: ensure_telemetry_config + run_tail for callers.
if [ "$\{BASH_SOURCE[0]:-$0\}" = "$0" ]; then
    run_tail
fi
